export const games = [
  {
    id: "codenames",
    title: "Codenames",
    blurb: "Two teams. One grid. No talking.",
    players: "4–8+",
    href: "./codenames/",
    status: "live",
    accent: "#c45c4a",
    soonNote: "",
  },
  {
    id: "thirty-seconds",
    title: "30 Seconds",
    blurb: "Race the board. Name five things. Pass the wine.",
    players: "4–12",
    href: "./thirty-seconds/",
    status: "live",
    accent: "#4a8b7a",
    soonNote: "",
  },
  {
    id: "close-enough",
    title: "Close Enough",
    blurb: "Guess the number. Closest wins. Furthest drinks.",
    players: "3–12",
    href: "./close-enough/",
    status: "live",
    accent: "#e4572e",
    soonNote: "",
  },
  {
    id: "connect-four",
    title: "Connect 4",
    blurb: "Drop a disc. Block the stack. Four wins it.",
    players: "2",
    href: "./connect-four/",
    status: "live",
    accent: "#f4c534",
    soonNote: "",
  },
  {
    id: "tic-tac-toe",
    title: "Tic-tac-toe",
    blurb: "Nine squares. Two rivals. Best of forever.",
    players: "2",
    href: "./tic-tac-toe/",
    status: "live",
    accent: "#5b93e6",
    soonNote: "",
  },
];
