// Playground service worker. Precaches the whole site so the hub and every
// game open offline, and caches Google Fonts as pages use them.
//
// The block between the precache markers is generated by
// `node scripts/gen-precache.mjs`. Do not edit it by hand.

// <precache>
const PRECACHE_VERSION = "7239da9822e6";
const PRECACHE_URLS = [
  "close-enough/css/styles.css",
  "close-enough/index.html",
  "close-enough/js/confetti.js",
  "close-enough/js/game.js",
  "close-enough/js/main.js",
  "close-enough/js/play.js",
  "close-enough/js/roster.js",
  "close-enough/js/router.js",
  "close-enough/js/score.js",
  "close-enough/js/standings.js",
  "close-enough/js/state.js",
  "close-enough/js/theme.js",
  "close-enough/js/ui.js",
  "close-enough/js/views/end.js",
  "close-enough/js/views/history.js",
  "close-enough/js/views/home.js",
  "close-enough/js/views/lobby.js",
  "close-enough/js/views/reveal.js",
  "close-enough/js/views/round.js",
  "close-enough/js/views/setup.js",
  "codenames/css/styles.css",
  "codenames/index.html",
  "codenames/js/game.js",
  "codenames/js/infoModal.js",
  "codenames/js/main.js",
  "codenames/js/router.js",
  "codenames/js/sound.js",
  "codenames/js/state.js",
  "codenames/js/theme.js",
  "codenames/js/timer.js",
  "codenames/js/ui.js",
  "codenames/js/views/assign.js",
  "codenames/js/views/end.js",
  "codenames/js/views/history.js",
  "codenames/js/views/home.js",
  "codenames/js/views/key.js",
  "codenames/js/views/play.js",
  "codenames/js/views/qr.js",
  "codenames/js/views/setup.js",
  "codenames/js/words.js",
  "codenames/vendor/qrcode.min.js",
  "css/hub.css",
  "icons/icon-180.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "icons/icon.svg",
  "index.html",
  "js/games.js",
  "js/hub.js",
  "js/pwa.js",
  "manifest.webmanifest",
  "thirty-seconds/css/styles.css",
  "thirty-seconds/index.html",
  "thirty-seconds/js/boardMap.js",
  "thirty-seconds/js/game.js",
  "thirty-seconds/js/main.js",
  "thirty-seconds/js/router.js",
  "thirty-seconds/js/sound.js",
  "thirty-seconds/js/state.js",
  "thirty-seconds/js/theme.js",
  "thirty-seconds/js/timer.js",
  "thirty-seconds/js/ui.js",
  "thirty-seconds/js/views/board.js",
  "thirty-seconds/js/views/end.js",
  "thirty-seconds/js/views/history.js",
  "thirty-seconds/js/views/home.js",
  "thirty-seconds/js/views/round.js",
  "thirty-seconds/js/views/setup.js",
  "thirty-seconds/js/words/dutch_culture.js",
  "thirty-seconds/js/words/en_general.js",
  "thirty-seconds/js/words/index.js",
  "thirty-seconds/js/words/movies.js",
  "thirty-seconds/js/words/music.js",
  "thirty-seconds/js/words/nl_general.js",
  "thirty-seconds/js/words/sports.js"
];
// </precache>

// Cache Storage is shared by everything on the origin, so cache names carry
// this deployment's path to keep other apps and other copies of the site apart.
const SCOPE_PATH = new URL(self.registration.scope).pathname;
const CACHE_PREFIX = "playground-";
const PRECACHE = `${CACHE_PREFIX}precache-${PRECACHE_VERSION}@${SCOPE_PATH}`;
const FONTS = `${CACHE_PREFIX}fonts-v1@${SCOPE_PATH}`;
const MAX_FONT_ENTRIES = 80;

const siteUrl = (path) => new URL(path, self.location.href).href;

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(PRECACHE);
      await Promise.all(PRECACHE_URLS.map((path) => precache(cache, path)));
      await self.skipWaiting();
    })(),
  );
});

async function precache(cache, path) {
  const url = siteUrl(path);
  const response = await fetch(url, { cache: "reload" });
  // A file deleted without regenerating the list must not block the update
  // forever; anything else (offline, 5xx) fails the install so it is retried.
  if (response.status === 404) {
    console.warn(`[sw] not precached, 404: ${path}`);
    return;
  }
  if (!response.ok) throw new Error(`[sw] precache ${path}: HTTP ${response.status}`);
  await cache.put(url, await withoutRedirect(response));
}

// Browsers refuse a redirected response for a page navigation, and some hosts
// redirect /index.html to /.
async function withoutRedirect(response) {
  if (!response.redirected) return response;
  return new Response(await response.blob(), {
    status: response.status,
    statusText: response.statusText,
    headers: response.headers,
  });
}

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keep = new Set([PRECACHE, FONTS]);
      const stale = (await caches.keys()).filter(
        (key) =>
          key.startsWith(CACHE_PREFIX) &&
          key.endsWith(`@${SCOPE_PATH}`) &&
          !keep.has(key),
      );
      await Promise.all(stale.map((key) => caches.delete(key)));
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin === self.location.origin) {
    event.respondWith(fromPrecache(request, url));
  } else if (url.hostname === "fonts.googleapis.com") {
    event.respondWith(fromFontCache(event, { revalidate: true }));
  } else if (url.hostname === "fonts.gstatic.com") {
    event.respondWith(fromFontCache(event, { revalidate: false }));
  }
});

async function fromPrecache(request, url) {
  const key = new URL(url);
  key.search = "";
  key.hash = "";
  if (key.pathname.endsWith("/")) key.pathname += "index.html";

  const cache = await caches.open(PRECACHE);
  const cached = await cache.match(key.href);
  if (cached) return cached;

  try {
    return await fetch(request);
  } catch (error) {
    if (request.mode === "navigate") {
      const fallback = await offlineRedirect(cache, key);
      if (fallback) return fallback;
    }
    throw error;
  }
}

// Offline, send "game" to "game/" when that folder is cached, else to the hub.
async function offlineRedirect(cache, key) {
  const folder = new URL(key);
  if (!folder.pathname.endsWith("/index.html")) {
    folder.pathname += "/";
    if (await cache.match(new URL("index.html", folder).href)) {
      return Response.redirect(folder.href, 302);
    }
  }
  if (await cache.match(siteUrl("index.html"))) {
    return Response.redirect(siteUrl("./"), 302);
  }
  return null;
}

// Stylesheets from fonts.googleapis.com are served from cache and refreshed in
// the background; font files on fonts.gstatic.com are immutable, so cache-first.
async function fromFontCache(event, { revalidate }) {
  const { request } = event;
  const cache = await caches.open(FONTS);
  const cached = await cache.match(request, { ignoreVary: true });
  if (cached && !revalidate) return cached;

  const network = fetch(request).then((response) => {
    if (response.ok || response.type === "opaque") {
      const copy = response.clone();
      event.waitUntil(cache.put(request, copy).then(() => trim(cache)));
    }
    return response;
  });
  if (!cached) return network;
  event.waitUntil(network.catch(() => {}));
  return cached;
}

async function trim(cache) {
  const keys = await cache.keys();
  const excess = keys.slice(0, Math.max(0, keys.length - MAX_FONT_ENTRIES));
  await Promise.all(excess.map((key) => cache.delete(key)));
}
