// ~400 classic Codenames-style words. Single-word entries only, capitalised
// for display. Sourced from the public original Codenames word list (the
// vocabulary itself is not protected — only the game's trademarks are).
export const WORDS = [
  "Africa", "Agent", "Air", "Alien", "Alps", "Amazon", "Ambulance", "America",
  "Angel", "Antarctica", "Apple", "Arm", "Atlantis", "Australia", "Aztec",
  "Back", "Ball", "Band", "Bank", "Bar", "Bark", "Bat", "Battery", "Beach",
  "Bear", "Beat", "Bed", "Beijing", "Bell", "Belt", "Berlin", "Bermuda",
  "Berry", "Bill", "Block", "Board", "Bolt", "Bomb", "Bond", "Boom", "Boot",
  "Bottle", "Bow", "Box", "Bridge", "Brush", "Buck", "Buffalo", "Bug",
  "Bugle", "Button",
  "Calf", "Canada", "Cap", "Capital", "Car", "Card", "Carrot", "Casino",
  "Cast", "Cat", "Cell", "Centaur", "Center", "Chair", "Change", "Charge",
  "Check", "Chest", "Chick", "China", "Chocolate", "Church", "Circle",
  "Cliff", "Cloak", "Club", "Code", "Cold", "Comic", "Compound", "Concert",
  "Conductor", "Contract", "Cook", "Copper", "Cotton", "Court", "Cover",
  "Crane", "Crash", "Cricket", "Cross", "Crown", "Cycle", "Czech",
  "Dance", "Date", "Day", "Death", "Deck", "Degree", "Diamond", "Dice",
  "Dinosaur", "Disease", "Doctor", "Dog", "Dragon", "Dress", "Drill",
  "Drop", "Duck", "Dwarf",
  "Eagle", "Egypt", "Embassy", "Engine", "England", "Europe", "Eye", "Face",
  "Fair", "Fall", "Fan", "Fence", "Field", "Fighter", "Figure", "File",
  "Film", "Fire", "Fish", "Flag", "Flute", "Fly", "Foot", "Force", "Forest",
  "Fork", "France", "Game", "Gas", "Genius", "Germany", "Ghost", "Giant",
  "Glass", "Glove", "Gold", "Grace", "Grass", "Greece", "Green", "Ground",
  "Ham", "Hand", "Hawk", "Head", "Heart", "Helicopter", "Himalayas", "Hole",
  "Hollywood", "Honey", "Hood", "Hook", "Horn", "Horse", "Horseshoe",
  "Hospital", "Hotel", "Ice", "Iceland", "India", "Iron", "Ivory", "Jack",
  "Jam", "Jet", "Jewel", "Jockey", "Jupiter", "Kangaroo", "Ketchup", "Key",
  "Kid", "King", "Kiwi", "Knife", "Knight", "Lab", "Lap", "Laser", "Lawyer",
  "Lead", "Lemon", "Leprechaun", "Life", "Light", "Limousine", "Line",
  "Link", "Lion", "Litter", "Loch Ness", "Lock", "Log", "London", "Luck",
  "Mail", "Mammoth", "Maple", "Marble", "March", "Mass", "Match", "Mercury",
  "Mexico", "Microscope", "Millionaire", "Mine", "Mint", "Missile", "Model",
  "Mole", "Moon", "Moscow", "Mount", "Mouse", "Mouth", "Mug",
  "Nail", "Needle", "Net", "New York", "Night", "Ninja", "Note", "Novel",
  "Nurse", "Nut", "Octopus", "Oil", "Olive", "Olympus", "Opera", "Orange",
  "Organ", "Palm", "Pan", "Pants", "Paper", "Parachute", "Park", "Part",
  "Pass", "Paste", "Penguin", "Phoenix", "Piano", "Pie", "Pilot", "Pin",
  "Pipe", "Pirate", "Pistol", "Pit", "Pitch", "Plane", "Plastic", "Plate",
  "Platypus", "Play", "Plot", "Point", "Poison", "Pole", "Police", "Pool",
  "Port", "Post", "Pound", "Press", "Princess", "Pumpkin", "Pupil",
  "Pyramid", "Queen", "Rabbit", "Racket", "Ray", "Revolution", "Ring",
  "Robin", "Robot", "Rock", "Rome", "Root", "Rose", "Roulette", "Round",
  "Row", "Ruler",
  "Satellite", "Saturn", "Scale", "School", "Scientist", "Scorpion",
  "Screen", "Scuba diver", "Seal", "Server", "Shadow", "Shakespeare",
  "Shark", "Ship", "Shoe", "Shop", "Shot", "Sink", "Skyscraper", "Slip",
  "Slug", "Smuggler", "Snow", "Snowman", "Sock", "Soldier", "Soul", "Sound",
  "Space", "Spell", "Spider", "Spike", "Spine", "Spot", "Spring", "Spy",
  "Square", "Stadium", "Staff", "Star", "State", "Stick", "Stock", "Straw",
  "Stream", "Strike", "String", "Sub", "Suit", "Superhero", "Swing",
  "Switch", "Table", "Tablet", "Tag", "Tail", "Tap", "Teacher", "Telescope",
  "Temple", "Theater", "Thief", "Thumb", "Tick", "Tie", "Time", "Tokyo",
  "Tooth", "Torch", "Tower", "Track", "Train", "Triangle", "Trip", "Trunk",
  "Tube", "Turkey", "Undertaker", "Unicorn", "Vacuum", "Van", "Vet",
  "Wake", "Wall", "War", "Washer", "Washington", "Watch", "Water", "Wave",
  "Web", "Well", "Whale", "Whip", "Wind", "Witch", "Worm", "Yard",
  // Extra commons to bring count up to ~400
  "Acorn", "Alarm", "Anchor", "Antelope", "Aquarius", "Arch", "Ash",
  "Astronaut", "Avalanche", "Avocado", "Badger", "Bagel", "Bakery",
  "Balance", "Balloon", "Bamboo", "Banana", "Bandage", "Banjo", "Barrel",
  "Basket", "Beacon", "Beard", "Beaver", "Beehive", "Beetle", "Biscuit",
  "Blade", "Blanket", "Blender", "Blossom", "Boomerang", "Bouquet",
  "Boxer", "Brain", "Branch", "Brass", "Brick", "Bubble", "Bucket",
  "Bullet", "Bunker", "Burger", "Cabin", "Cable", "Cactus", "Camera",
  "Camp", "Candle", "Canoe", "Canvas", "Canyon", "Carnival", "Castle",
  "Caterpillar", "Cathedral", "Cave", "Ceiling", "Chain", "Chalk",
  "Chameleon", "Channel", "Chapter", "Charcoal", "Cheese", "Cherry",
  "Chimney", "Chipmunk", "Clarinet", "Cloud", "Clover", "Coast", "Cobra",
  "Cocoon", "Coffee", "Comet", "Compass", "Console", "Coral", "Cradle",
  "Crater", "Crayon", "Cucumber", "Cupcake", "Curtain", "Cushion",
  "Daisy", "Dart", "Dawn", "Delta", "Desert", "Diary", "Dolphin", "Donkey",
  "Doorbell", "Dragonfly", "Dune", "Dust", "Echo", "Eclipse", "Eel", "Elf",
  "Ember", "Engineer", "Envelope", "Falcon", "Feather", "Ferry", "Fiddle",
  "Firework", "Fjord", "Flame", "Flask", "Flock", "Forge", "Fossil",
  "Fountain", "Fox", "Frost", "Galaxy", "Gallery", "Garden", "Gargoyle",
  "Garlic", "Gazelle", "Geyser", "Glacier", "Goblet", "Goblin", "Granite",
  "Grape", "Grizzly", "Hammer", "Hammock", "Harbor", "Harp", "Harvest",
  "Hedgehog", "Heron", "Hieroglyph", "Hive", "Hurricane", "Igloo", "Iguana",
  "Inkwell", "Island", "Ivy", "Jaguar", "Jellyfish", "Jungle", "Kayak",
  "Kelp", "Kennel", "Kettle", "Kilt", "Kite", "Koala", "Lagoon", "Lantern",
  "Lava", "Lemur", "Library", "Lighthouse", "Lily", "Lizard", "Lobster",
  "Locker", "Lullaby", "Mango", "Manor", "Map", "Marsh", "Maze", "Meadow",
  "Medal", "Mermaid", "Meteor", "Mirror", "Monk", "Monster", "Mosaic",
  "Moth", "Mountain", "Muffin", "Muscle", "Museum", "Mushroom", "Nebula",
  "Nectar", "Nest", "Nettle", "Notebook", "Nugget", "Oasis", "Obsidian",
  "Onion", "Opal", "Orchid", "Otter", "Owl", "Oyster", "Paddle", "Pagoda",
  "Pancake", "Panda", "Paradise", "Parrot", "Patio", "Pawn", "Peacock",
  "Pebble", "Pelican", "Pencil", "Pendant", "Petal", "Pickle", "Pillow",
  "Pinecone", "Pixel", "Plum", "Pollen", "Pond", "Poppy", "Portal",
  "Potion", "Prairie", "Prism", "Pulse", "Puppet", "Quartz", "Quill",
  "Quilt", "Raccoon", "Radar", "Raft", "Rainbow", "Rapid", "Reef", "Relay",
  "Reptile", "Rhino", "Riddle", "River", "Rocket", "Rune", "Saddle",
  "Sailor", "Salt", "Sandal", "Sapphire", "Scarf", "Sculpture", "Seagull",
  "Seashell", "Seed", "Sentinel", "Sherbet", "Shrine", "Shuttle", "Sigil",
  "Silk", "Silver", "Skate", "Sketch", "Skull", "Slate", "Sled", "Sleigh",
  "Snail", "Snake", "Sparrow", "Sphinx", "Spire", "Sponge", "Squid",
  "Squirrel", "Stamp", "Statue", "Stew", "Storm", "Stove", "Strawberry",
  "Sundial", "Sunflower", "Sunset", "Surge", "Swamp", "Swan", "Sword",
  "Symbol", "Syrup", "Talon", "Tambourine", "Tangerine", "Tapestry",
  "Teapot", "Tent", "Thorn", "Throne", "Thunder", "Tiger", "Toad", "Tomb",
  "Topaz", "Tornado", "Tortoise", "Totem", "Toucan", "Trail", "Treasure",
  "Trumpet", "Tulip", "Tuna", "Tundra", "Turtle", "Tusk", "Umbrella",
  "Valley", "Vase", "Velvet", "Vine", "Violin", "Volcano", "Vortex",
  "Vulture", "Walrus", "Wand", "Wax", "Whisker", "Whistle", "Willow",
  "Window", "Wizard", "Wolf", "Wreath", "Yacht", "Yarn", "Zebra"
];

// Deduplicate just in case (preserves order, first occurrence wins).
const seen = new Set();
export const WORD_LIST = WORDS.filter((w) => {
  const key = w.toLowerCase();
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});
