#!/usr/bin/env python3
"""Emit original 30 Seconds word-pack JS modules. Facts only — not copied from any commercial deck."""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "js" / "words"


def unique(words):
    seen = set()
    out = []
    dups = []
    for w in words:
        w = " ".join(w.split())
        key = w.casefold()
        if key in seen:
            dups.append(w)
            continue
        seen.add(key)
        out.append(w)
    if dups:
        print(f"  dropped {len(dups)} in-pack dupes: {dups[:8]}")
    return out


NL_GENERAL = unique([
    "Max Verstappen", "Johan Cruijff", "André Hazes", "André van Duin", "Chantal Janzen",
    "Linda de Mol", "Gordon", "Guus Meeuwis", "Anouk", "Armin van Buuren",
    "Tiësto", "Martin Garrix", "Duncan Laurence", "Eva Jinek", "Matthijs van Nieuwkerk",
    "Beau van Erven Dorens", "Humberto Tan", "Sylvana Simons", "Thierry Baudet", "Mark Rutte",
    "Willem-Alexander", "Máxima", "Prinses Amalia", "Prins Bernhard", "Anne Frank",
    "Vincent van Gogh", "Rembrandt", "Erasmus", " Spinoza", "Piet Mondriaan",
    "M.C. Escher", "Dick Bruna", "Wim T. Schippers", "Paul de Leeuw", "Youp van 't Hek",
    "Freek de Jonge", "Theo Maassen", "Jochem Myjer", "Claudia de Breij", "Najib Amhali",
    "Ali B", "Yes-R", "Broederliefde", "Snelle", "Maan",
    "Davina Michelle", "Ilse DeLange", "Trijntje Oosterhuis", "Marco Borsato", "Jan Smit",
    "Frans Bauer", "Nick & Simon", "Acda en De Munnik", "BLØF", "Doe Maar",
    "Golden Earring", "Anouk", "Within Temptation", "Epica", "Focus",
    "Amsterdam", "Rotterdam", "Utrecht", "Den Haag", "Eindhoven",
    "Groningen", "Maastricht", "Haarlem", "Leiden", "Delft",
    "Nijmegen", "Arnhem", "Tilburg", "Breda", "Zwolle",
    "Almere", "Amersfoort", "Apeldoorn", "Enschede", "Leeuwarden",
    "Middelburg", "Vlissingen", "Scheveningen", "Zandvoort", "Volendam",
    "Marken", "Giethoorn", "Kinderdijk", "Keukenhof", "Efteling",
    "Madurodam", "Artis", "NEMO", "Rijksmuseum", "Van Gogh Museum",
    "Anne Frank Huis", "Euromast", "Erasmusbrug", "Domtoren", "Martinitoren",
    "Afsluitdijk", "Deltawerken", "Waddeneilanden", "Texel", "Terschelling",
    "Schiphol", "NS", "OV-chipkaart", "fiets", "brommer",
    "gracht", "molen", "klompen", "tulpen", "kaas",
    "haring", "stroopwafel", "drop", "hagelslag", "pindakaas",
    "kroket", "bitterballen", "poffertjes", "pannenkoeken", "erwtensoep",
    "stamppot", "boerenkool", "hutspot", "kapucijners", "oliebol",
    "appeltaart", "vla", "chocoladeletter", "pepernoten", "speculaas",
    "tompouce", "bossche bol", "ontbijtkoek", "beschuit", "pindasaus",
    "friet", "mayo", "saté", "rijsttafel", "nasi",
    "bami", "loempia", "kibbeling", "lekkerbek", "patatje oorlog",
    "HEMA", "Albert Heijn", "Jumbo", "Kruidvat", "Action",
    "Blokker", "Ikea", "MediaMarkt", "Coolblue", "Bol.com",
    "KPN", "Vodafone", "ING", "Rabobank", "ABN AMRO",
    "KLM", "TUI", "ANWB", "PostNL", "Belastingdienst",
    "Rijkswaterstaat", "politie", "brandweer", "ambulance", "huisarts",
    "tandarts", "apotheek", "supermarkt", "markt", "braderie",
    "kermis", "koningsdag", "sinterklaas", "kerstmarkt", "oud en nieuw",
    "vuurwerk", "oliebollenkraam", "terras", "bruin café", "coffeeshop",
    "snackbar", "patatzaak", "visboer", "bakker", "slager",
    "kapper", "sauna", "zwembad", "sportschool", "voetbalveld",
    "ijsstadion", "schaatsbaan", "speeltuin", "bos", "duinen",
    "polder", "dijk", "sloot", "molenwiek", "klokkentoren",
    "stadhuis", "bibliotheek", "zwemband", "regenjas", "paraplu",
    "fietstas", "bagagedrager", "trambaan", "metro", "veerboot",
    "pont", "waterfiets", "kano", "zeilboot", "woonboot",
    "huisje-boompje-beestje", "buren", "postcode", "kenteken", "rijbewijs",
    "BSN", "DigiD", "iDEAL", "pinpas", "contant",
    "fooienpot", "borrel", "borrelnootjes", "kaasstengels", "bittergarnituur",
    "jenever", "advocaat", " likorette", "witte wijn", "rode wijn",
    "Spa rood", "Spa blauw", "Chocomel", "Fristi", "Rivella",
    "Grolsch", "Heineken", "Amstel", "Bavaria", "Jupiler",
    "Big Brother", "The Voice", "Wie is de Mol", "Boer zoekt Vrouw", "Expeditie Robinson",
    "Flikken Maastricht", "Baantjer", "Goede Tijden", "Sesamstraat", "Bassie en Adriaan",
    "Kameleon", "Piet Piraat", "Samson en Gert", "K3", "Plop",
    "Nijntje", "Dikkie Dik", "Jip en Janneke", "Kikker", "Dolfje Weerwolfje",
    "Harry Potter", "Koning van Katoren", "Kruistocht in spijkerbroek", "Oorlogswinter", "Soldaat van Oranje",
    "Zwarte Piet", "Kerstman", "Paashaas", "tandenfee", "Sinterklaasjournaal",
    "NOS Journaal", "Hart van Nederland", "RTL Boulevard", "Shownieuws", "De Wereld Draait Door",
    "College Tour", "Pauw", "Jinek", "Op1", "Khalid & Sophie",
    "Voetbal International", "Studio Sport", "Formul1", "Tour de France", "Elfstedentocht",
    "Vierdaagse", "Pinkpop", "Lowlands", "Mysteryland", "Tomorrowland",
    "Koninginnedag", "Bevrijdingsdag", "Dodenherdenking", "Prinsjesdag", "troonrede",
    "Eerste Kamer", "Tweede Kamer", "gemeenteraad", "burgemeester", "wethouder",
    "koningshuis", "gouden koets", "balkon", "Paleis Noordeinde", "Huis ten Bosch",
    "Paleis Soestdijk", "Dam", "Museumplein", "Vondelpark", "Kralingse Bos",
    "Hoge Veluwe", "Biesbosch", "Oosterschelde", "IJsselmeer", "Noordzee",
    "Rijn", "Maas", "Waal", "IJssel", "Amstel",
    "goudse kaas", "edammer", "leidse kaas", "boerenkaas", "smeerkaas",
    "ontbijt", "lunch", "avondeten", "tussendoortje", "koffietijd",
    "beschuit met muisjes", "zwanger", "kraamvisite", "huiswarming", "vrijgezellenfeest",
    "bruiloft", "begrafenis", "sjaal", "muts", "handschoenen",
    "klompenpad", "wandelbos", "natuurspeeltuin", "kinderboerderij", "minicamping",
])

EN_GENERAL = unique([
    "Albert Einstein", "Isaac Newton", "Charles Darwin", "Marie Curie", "Stephen Hawking",
    "Leonardo da Vinci", "Michelangelo", "Picasso", "Frida Kahlo", "Andy Warhol",
    "Shakespeare", "Charles Dickens", "Jane Austen", "J.K. Rowling", "Tolkien",
    "Winston Churchill", "Abraham Lincoln", "Nelson Mandela", "Mahatma Gandhi", "Martin Luther King",
    "Barack Obama", "Donald Trump", "Joe Biden", "Angela Merkel", "Vladimir Putin",
    "Queen Elizabeth", "King Charles", "Princess Diana", "Prince Harry", "Meghan Markle",
    "The Pope", "Dalai Lama", "Oprah Winfrey", "Ellen DeGeneres", "David Attenborough",
    "Gordon Ramsay", "Jamie Oliver", "Martha Stewart", "Julia Child", "Anthony Bourdain",
    "Elon Musk", "Jeff Bezos", "Bill Gates", "Steve Jobs", "Mark Zuckerberg",
    "Taylor Swift", "Beyoncé", "Rihanna", "Lady Gaga", "Adele",
    "Ed Sheeran", "Bruno Mars", "The Weeknd", "Drake", "Kanye West",
    "Michael Jackson", "Elvis Presley", "Madonna", "Prince", "David Bowie",
    "The Beatles", "The Rolling Stones", "Queen", "ABBA", "U2",
    "Tom Cruise", "Brad Pitt", "Leonardo DiCaprio", "Johnny Depp", "Will Smith",
    "Denzel Washington", "Tom Hanks", "Morgan Freeman", "Robert De Niro", "Al Pacino",
    "Meryl Streep", "Scarlett Johansson", "Jennifer Lawrence", "Natalie Portman", "Emma Stone",
    "Angelina Jolie", "Nicole Kidman", "Charlize Theron", "Sandra Bullock", "Julia Roberts",
    "Keanu Reeves", "Chris Hemsworth", "Chris Evans", "Robert Downey Jr.", "Hugh Jackman",
    "London", "Paris", "New York", "Los Angeles", "Tokyo",
    "Rome", "Berlin", "Madrid", "Barcelona", "Lisbon",
    "Athens", "Cairo", "Dubai", "Sydney", "Melbourne",
    "Toronto", "Vancouver", "Chicago", "San Francisco", "Miami",
    "Las Vegas", "Hawaii", "Iceland", "Norway", "Sweden",
    "Finland", "Denmark", "Ireland", "Scotland", "Wales",
    "England", "Canada", "United States", "Mexico", "Brazil",
    "Argentina", "Chile", "Peru", "Colombia", "South Africa",
    "Kenya", "Egypt", "Morocco", "India", "China",
    "Japan", "South Korea", "Thailand", "Vietnam", "Indonesia",
    "Australia", "New Zealand", "Antarctica", "Sahara", "Amazon rainforest",
    "Mount Everest", "Grand Canyon", "Niagara Falls", "Statue of Liberty", "Eiffel Tower",
    "Big Ben", "Tower Bridge", "Colosseum", "Acropolis", "Pyramids of Giza",
    "Great Wall of China", "Taj Mahal", "Machu Picchu", "Christ the Redeemer", "Sydney Opera House",
    "Golden Gate Bridge", "Times Square", "Hollywood", "Broadway", "Wall Street",
    "White House", "Buckingham Palace", "Tower of London", "Stonehenge", "Loch Ness",
    "coffee", "tea", "pizza", "hamburger", "hot dog",
    "sushi", "taco", "burrito", "spaghetti", "lasagna",
    "pancake", "waffle", "doughnut", "cupcake", "ice cream",
    "chocolate", "popcorn", "pretzel", "bagel", "sandwich",
    "ketchup", "mustard", "mayonnaise", "barbecue", "breakfast",
    "umbrella", "backpack", "suitcase", "passport", "camera",
    "smartphone", "laptop", "headphones", "remote control", "microwave",
    "refrigerator", "toaster", "blender", "vacuum cleaner", "washing machine",
    "toothbrush", "shampoo", "soap", "towel", "pillow",
    "alarm clock", "calendar", "dictionary", "newspaper", "magazine",
    "library", "museum", "airport", "train station", "subway",
    "taxi", "bus", "bicycle", "motorcycle", "helicopter",
    "submarine", "yacht", "cruise ship", "hot air balloon", "parachute",
    "firefighter", "police officer", "doctor", "nurse", "teacher",
    "pilot", "astronaut", "chef", "waiter", "farmer",
    "lawyer", "judge", "detective", "spy", "pirate",
    "knight", "princess", "wizard", "vampire", "zombie",
    "robot", "dinosaur", "unicorn", "dragon", "mermaid",
    "elephant", "giraffe", "penguin", "kangaroo", "koala",
    "dolphin", "whale", "shark", "octopus", "jellyfish",
    "eagle", "owl", "peacock", "flamingo", "parrot",
    "lion", "tiger", "cheetah", "wolf", "fox",
    "bear", "panda", "sloth", "hedgehog", "squirrel",
    "rainbow", "thunderstorm", "earthquake", "volcano", "avalanche",
    "desert", "jungle", "glacier", "waterfall", "island",
    "compass", "telescope", "microscope", "magnet", "battery",
    "lightbulb", "candle", "matchstick", "flashlight", "lantern",
    "scissors", "hammer", "screwdriver", "wrench", "needle",
    "button", "zipper", "pocket", "sleeve", "collar",
    "Monday", "Friday", "weekend", "midnight", "sunrise",
    "Christmas", "Halloween", "Thanksgiving", "Valentine's Day", "New Year's Eve",
    "Olympics", "World Cup", "Super Bowl", "Wimbledon", "Tour de France",
    "Google", "Apple", "Microsoft", "Amazon", "Netflix",
    "YouTube", "Instagram", "TikTok", "WhatsApp", "Spotify",
    "McDonald's", "Starbucks", "Coca-Cola", "Pepsi", "Ikea",
    "Lego", "Barbie", "PlayStation", "Nintendo", "Xbox",
    "Harry Potter", "Sherlock Holmes", "James Bond", "Superman", "Batman",
    "Spider-Man", "Wonder Woman", "Iron Man", "Hulk", "Thor",
    "Mickey Mouse", "Donald Duck", "Winnie the Pooh", "SpongeBob", "Pikachu",
    "Mario", "Sonic", "Link", "Master Chief", "Lara Croft",
])

MOVIES = unique([
    "Titanic", "Avatar", "The Godfather", "Pulp Fiction", "Forrest Gump",
    "The Shawshank Redemption", "The Dark Knight", "Inception", "Interstellar", "The Matrix",
    "Jurassic Park", "Jaws", "E.T.", "Star Wars", "The Empire Strikes Back",
    "Return of the Jedi", "The Force Awakens", "The Phantom Menace", "Raiders of the Lost Ark", "Indiana Jones",
    "Back to the Future", "Ghostbusters", "Gremlins", "The Goonies", "Home Alone",
    "Die Hard", "Terminator", "Terminator 2", "Alien", "Aliens",
    "Predator", "RoboCop", "Total Recall", "Blade Runner", "Mad Max",
    "The Lord of the Rings", "The Fellowship of the Ring", "The Two Towers", "The Return of the King", "The Hobbit",
    "Harry Potter and the Philosopher's Stone", "Harry Potter and the Chamber of Secrets", "Harry Potter and the Prisoner of Azkaban", "Harry Potter and the Goblet of Fire", "Harry Potter and the Deathly Hallows",
    "The Hunger Games", "Twilight", "The Fault in Our Stars", "La La Land", "Whiplash",
    "Parasite", "Everything Everywhere All at Once", "Oppenheimer", "Barbie", "Dune",
    "The Batman", "Joker", "Black Panther", "Avengers: Endgame", "Avengers: Infinity War",
    "Iron Man", "Captain America", "Thor: Ragnarok", "Guardians of the Galaxy", "Doctor Strange",
    "Spider-Man: No Way Home", "The Amazing Spider-Man", "Deadpool", "Logan", "X-Men",
    "Frozen", "Moana", "Encanto", "Coco", "Inside Out",
    "Toy Story", "Finding Nemo", "The Incredibles", "Up", "Wall-E",
    "Shrek", "Shrek 2", "Kung Fu Panda", "How to Train Your Dragon", "The Lego Movie",
    "The Lion King", "Aladdin", "Beauty and the Beast", "The Little Mermaid", "Mulan",
    "Snow White", "Cinderella", "Sleeping Beauty", "Peter Pan", "Bambi",
    "The Sound of Music", "West Side Story", "Grease", "Mamma Mia", "The Greatest Showman",
    "Chicago", "Les Misérables", "Hamilton", "Wicked", "Mary Poppins",
    "Pretty Woman", "Notting Hill", "Love Actually", "The Notebook", "Pride and Prejudice",
    "Dirty Dancing", "Ghost", "Sleepless in Seattle", "When Harry Met Sally", "10 Things I Hate About You",
    "Mean Girls", "Clueless", "Legally Blonde", "Bridget Jones's Diary", "The Devil Wears Prada",
    "Ocean's Eleven", "The Italian Job", "Catch Me If You Can", "The Wolf of Wall Street", "The Social Network",
    "Fight Club", "Se7en", "Gone Girl", "Zodiac", "The Silence of the Lambs",
    "The Exorcist", "The Shining", "Halloween", "Scream", "A Nightmare on Elm Street",
    "Get Out", "Hereditary", "The Conjuring", "It", "The Ring",
    "Mission: Impossible", "James Bond", "Casino Royale", "Skyfall", "No Time to Die",
    "John Wick", "Taken", "The Bourne Identity", "Jason Bourne", "Kingsman",
    "Pirates of the Caribbean", "The Mummy", "National Treasure", "Night at the Museum", "Jumanji",
    "The Truman Show", "The Grand Budapest Hotel", "Amélie", "Life is Beautiful", "Cinema Paradiso",
    "Spirited Away", "My Neighbor Totoro", "Princess Mononoke", "Akira", "Your Name",
    "The Intouchables", "Amélie", "Blue Is the Warmest Colour", "Portrait of a Lady on Fire", "Crouching Tiger Hidden Dragon",
    "Soldaat van Oranje", "Zwartboek", "Turks Fruit", "Karakter", "De Aanslag",
    "Alles is Liefde", "Soof", "Gooische Vrouwen", "New Kids Turbo", "Bon Voijage",
    "Minoes", "Kruistocht in spijkerbroek", "Oorlogswinter", "Bridget", "Loenatik",
    "Flodder", "Schatjes", "Ciske de Rat", "Fanfare", "Soldaat van Oranje",
    "Friends", "The Office", "Breaking Bad", "Game of Thrones", "Stranger Things",
    "The Crown", "The Witcher", "Wednesday", "Squid Game", "Money Heist",
    "Dark", "The Bear", "Succession", "Ted Lasso", "Only Murders in the Building",
    "Seinfeld", "Frasier", "How I Met Your Mother", "Brooklyn Nine-Nine", "Parks and Recreation",
    "The Simpsons", "Family Guy", "South Park", "BoJack Horseman", "Rick and Morty",
    "Black Mirror", "Westworld", "Lost", "Prison Break", "24",
    "Grey's Anatomy", "ER", "House", "The Good Doctor", "Scrubs",
    "Law & Order", "CSI", "True Detective", "Sherlock", "Luther",
    "Downton Abbey", "Bridgerton", "Outlander", "The Handmaid's Tale", "Big Little Lies",
    "Sex and the City", "Girls", "Euphoria", "Skins", "Gossip Girl",
    "The Walking Dead", "True Blood", "Buffy the Vampire Slayer", "Supernatural", "Doctor Who",
    "Star Trek", "The Mandalorian", "Andor", "House of the Dragon", "The Last of Us",
    "Peaky Blinders", "Narcos", "Ozark", "Better Call Saul", "Fargo",
    "The Big Bang Theory", "Two and a Half Men", "Modern Family", "Schitt's Creek", "Community",
    "Fawlty Towers", "Monty Python", "Blackadder", "The IT Crowd", "Sherlock",
    "Baantjer", "Flikken Maastricht", "Penoza", "Undercover", "De Luizenmoeder",
    "Wie is de Mol", "Boer zoekt Vrouw", "Expeditie Robinson", "The Voice of Holland", "Holland's Next Top Model",
    "Goede Tijden Slechte Tijden", "Onderweg naar Morgen", "Spangas", "Het Huis Anubis", "Koefnoen",
    "Jiskefet", "Van Kooten en De Bie", "Koot & Bie", "Tata's", "New Kids",
    "Toen was geluk heel gewoon", "Zaai", "Kees & Co", "Samson en Gert", "Bassie en Adriaan",
    "Sesamstraat", "Teletubbies", "PAW Patrol", "Bluey", "Peppa Pig",
    "The Lion Guard", "Dora the Explorer", "SpongeBob SquarePants", "The Fairly OddParents", "Avatar: The Last Airbender",
    "Arcane", "The Boys", "Fallout", "The Penguin", "Loki",
    "WandaVision", "Ms. Marvel", "Moon Knight", "Hawkeye", "She-Hulk",
    "Knives Out", "Glass Onion", "Murder on the Orient Express", "Clue", "The Menu",
    " cocoon", "The Notebook", "A Star Is Born", "Bohemian Rhapsody", "Elvis",
    "Rocketman", "Walk the Line", "Ray", "Straight Outta Compton", "8 Mile",
])

MUSIC = unique([
    "The Beatles", "The Rolling Stones", "Led Zeppelin", "Pink Floyd", "Queen",
    "AC/DC", "Metallica", "Nirvana", "Pearl Jam", "Red Hot Chili Peppers",
    "U2", "Coldplay", "Radiohead", "Oasis", "Blur",
    "ABBA", "Bee Gees", "The Beach Boys", "The Who", "The Doors",
    "David Bowie", "Elton John", "Billy Joel", "Bruce Springsteen", "Bob Dylan",
    "Johnny Cash", "Willie Nelson", "Dolly Parton", "Taylor Swift", "Carrie Underwood",
    "Madonna", "Michael Jackson", "Prince", "Whitney Houston", "Mariah Carey",
    "Celine Dion", "Adele", "Amy Winehouse", "Duffy", "Sia",
    "Beyoncé", "Rihanna", "Lady Gaga", "Katy Perry", "Britney Spears",
    "Christina Aguilera", "Jennifer Lopez", "Shakira", "Nelly Furtado", "Dua Lipa",
    "Billie Eilish", "Olivia Rodrigo", "Ariana Grande", "Miley Cyrus", "Selena Gomez",
    "Harry Styles", "Ed Sheeran", "Sam Smith", "Shawn Mendes", "Justin Bieber",
    "The Weeknd", "Drake", "Kanye West", "Jay-Z", "Eminem",
    "Snoop Dogg", "Dr. Dre", "Tupac", "The Notorious B.I.G.", "Kendrick Lamar",
    "Travis Scott", "Post Malone", "Lil Nas X", "Doja Cat", "Nicki Minaj",
    "Bob Marley", "Jimmy Cliff", "UB40", "Sean Paul", "Shaggy",
    "Stevie Wonder", "Aretha Franklin", "Tina Turner", "James Brown", "Marvin Gaye",
    "Diana Ross", "The Supremes", "The Temptations", "Earth Wind & Fire", "Chic",
    "Daft Punk", "The Chemical Brothers", "Fatboy Slim", "Calvin Harris", "David Guetta",
    "Avicii", "Swedish House Mafia", "Kygo", "Marshmello", "Deadmau5",
    "Tiësto", "Armin van Buuren", "Martin Garrix", "Hardwell", "Oliver Heldens",
    "André Hazes", "Frans Bauer", "Jan Smit", "Guus Meeuwis", "Marco Borsato",
    "Acda en De Munnik", "BLØF", "Doe Maar", "Golden Earring", "The Scene",
    "Anouk", "Ilse DeLange", "Tri jntje Oosterhuis", "Within Temptation", "Epica",
    "Kensington", "Chef'Special", "De Jeugd van Tegenwoordig", "Kraantje Pappie", "Ronnie Flex",
    "Lil' Kleine", "Broederliefde", "Snelle", "Maan", "Davina Michelle",
    "Duncan Laurence", "S10", "Claude", "Joost", "Goldband",
    "Froukje", "Eefje de Visser", "Spinvis", "Van Dik Hout", "Rowwen Hèze",
    "Normaal", "Heideroosjes", "Di-rect", "Kane", "VanVelzen",
    "Racoon", "Nielson", "Miss Montreal", "Douwe Bob", "Waylon",
    "The Common Linnets", "Nick & Simon", "3JS", "Volumia!", "Krezip",
    "Bohemian Rhapsody", "Don't Stop Me Now", "We Will Rock You", "We Are the Champions", "Somebody to Love",
    "Stairway to Heaven", "Hotel California", "Sweet Child o' Mine", "Smells Like Teen Spirit", "Wonderwall",
    "Hey Jude", "Let It Be", "Yesterday", "Come Together", "Help!",
    "Billie Jean", "Thriller", "Beat It", "Smooth Criminal", "Bad",
    "Like a Prayer", "Vogue", "Material Girl", "Hung Up", "Music",
    "Rolling in the Deep", "Someone Like You", "Hello", "Skyfall", "Set Fire to the Rain",
    "Shape of You", "Perfect", "Thinking Out Loud", "Bad Habits", "Photograph",
    "Blinding Lights", "Starboy", "Save Your Tears", "The Hills", "Can't Feel My Face",
    "Old Town Road", "Drivers License", "Good 4 U", "Anti-Hero", "Shake It Off",
    "Blank Space", "Love Story", "You Belong with Me", "All Too Well", "Cruel Summer",
    "Umbrella", "Diamonds", "Stay", "We Found Love", "Only Girl",
    "Poker Face", "Bad Romance", "Shallow", "Born This Way", "Just Dance",
    "Single Ladies", "Halo", "Crazy in Love", "Formation", "Texas Hold 'Em",
    "Despacito", "Macarena", "Gangnam Style", "Baby Shark", "Happy",
    "Uptown Funk", "Get Lucky", "Wake Me Up", "Levels", "Titanium",
    "I Gotta Feeling", "Mr. Brightside", "Take On Me", "Africa", "Don't Stop Believin'",
    "Sweet Caroline", "Livin' on a Prayer", "Eye of the Tiger", "We Didn't Start the Fire", "Piano Man",
    "Imagine", "What a Wonderful World", "My Way", "New York New York", "Fly Me to the Moon",
    "La Bamba", "Guantanamera", "Bésame Mucho", "La Vie en Rose", "Non, je ne regrette rien",
    "jazz", "blues", "rock", "pop", "hip hop",
    "reggae", "country", "folk", "classical", "opera",
    "disco", "funk", "soul", "R&B", "techno",
    "house", "trance", "drum and bass", "gabber", "hardstyle",
    "metal", "punk", "indie", "k-pop", "latin",
    "guitar", "piano", "drums", "violin", "saxophone",
    "trumpet", "harmonica", "ukulele", "bass guitar", "synthesizer",
    "microphone", "karaoke", "festival", "concert", "album",
    "single", "remix", "cover", "duet", "choir",
    "Eurovision", "Grammy", "MTV", "Top 40", "Spotify Wrapped",
    "Woodstock", "Glastonbury", "Coachella", "Pinkpop", "Lowlands",
    "Tomorrowland", "Mysteryland", "Awakenings", "Defqon.1", "Dance Valley",
    "Het Concertgebouw", "Paradiso", "Melkweg", "Ahoy", "Ziggo Dome",
    "Johan Cruijff Arena", "GelreDome", "De Kuip", "AFAS Live", "013 Tilburg",
    "Breng me naar het water", "Het is een nacht", "Zij gelooft in mij", "Mag ik dan bij jou", "Blijf bij mij",
    "15 miljoen mensen", "Radar Love", "When the Lady Smiles", "Twilight Zone", "Radar Love",
    "Iedereen is van de wereld", "Kronenburg Park", "Zij maakt het verschil", "Onderweg", "Harder dan ik hebben kan",
    "They Don't Know", "Nobody Else", "Animals", "Pizza", "In the Name of Love",
    "This Is What It Feels Like", "Adagio for Strings", "Silence", "Gouryella", "Traffic",
])

SPORTS = unique([
    "football", "soccer", "American football", "rugby", "cricket",
    "baseball", "basketball", "volleyball", "handball", "hockey",
    "ice hockey", "field hockey", "tennis", "table tennis", "badminton",
    "squash", "golf", "bowling", "billiards", "snooker",
    "darts", "archery", "fencing", "boxing", "MMA",
    "wrestling", "judo", "karate", "taekwondo", "kung fu",
    "swimming", "diving", "water polo", "synchronized swimming", "rowing",
    "sailing", "surfing", "windsurfing", "kitesurfing", "canoeing",
    "kayaking", "cycling", "mountain biking", "BMX", "speed skating",
    "figure skating", "ice dancing", "ski jumping", "alpine skiing", "cross-country skiing",
    "snowboarding", "bobsleigh", "luge", "skeleton", "biathlon",
    "athletics", "marathon", "sprint", "hurdles", "relay",
    "long jump", "high jump", "pole vault", "shot put", "javelin",
    "discus", "hammer throw", "decathlon", "triathlon", "pentathlon",
    "gymnastics", "rhythmic gymnastics", "trampolining", "weightlifting", "powerlifting",
    "climbing", "bouldering", "orienteering", "horse riding", "dressage",
    "show jumping", "polo", "formula 1", "MotoGP", "rally",
    "NASCAR", "IndyCar", "karting", "e-sports", "chess",
    "poker", "bridge", "curling", "lacrosse", "Gaelic football",
    "Max Verstappen", "Lewis Hamilton", "Michael Schumacher", "Ayrton Senna", "Sebastian Vettel",
    "Charles Leclerc", "Lando Norris", "Fernando Alonso", "Kimi Räikkönen", "Niki Lauda",
    "Red Bull Racing", "Ferrari", "Mercedes", "McLaren", "Aston Martin",
    "Lionel Messi", "Cristiano Ronaldo", "Pelé", "Diego Maradona", "Zinedine Zidane",
    "Ronaldinho", "Neymar", "Kylian Mbappé", "Erling Haaland", "Kevin De Bruyne",
    "Johan Cruijff", "Marco van Basten", "Ruud Gullit", "Frank Rijkaard", "Dennis Bergkamp",
    "Patrick Kluivert", "Edgar Davids", "Clarence Seedorf", "Wesley Sneijder", "Arjen Robben",
    "Robin van Persie", "Dirk Kuyt", "Rafael van der Vaart", "Memphis Depay", "Virgil van Dijk",
    "Frenkie de Jong", "Matthijs de Ligt", "Cody Gakpo", "Xavi Simons", "Donyell Malen",
    "Ajax", "Feyenoord", "PSV", "AZ Alkmaar", "FC Utrecht",
    "FC Twente", "Vitesse", "Sparta Rotterdam", "NEC Nijmegen", "Go Ahead Eagles",
    "Manchester United", "Manchester City", "Liverpool", "Arsenal", "Chelsea",
    "Tottenham", "Real Madrid", "Barcelona", "Atlético Madrid", "Bayern Munich",
    "Borussia Dortmund", "Juventus", "AC Milan", "Inter Milan", "Napoli",
    "Paris Saint-Germain", "Benfica", "Porto", "Sporting Lisbon", "Celtic",
    "World Cup", "European Championship", "Champions League", "Europa League", "Eredivisie",
    "Premier League", "La Liga", "Bundesliga", "Serie A", "Ligue 1",
    "Super Bowl", "NBA Finals", "World Series", "Stanley Cup", "Wimbledon",
    "Roland Garros", "US Open", "Australian Open", "The Masters", "Tour de France",
    "Giro d'Italia", "Vuelta", "Olympics", "Paralympics", "Commonwealth Games",
    "Roger Federer", "Rafael Nadal", "Novak Djokovic", "Serena Williams", "Venus Williams",
    "Steffi Graf", "Andre Agassi", "Pete Sampras", "Maria Sharapova", "Naomi Osaka",
    "Iga Świątek", "Carlos Alcaraz", "Jannik Sinner", "Andy Murray", "Richard Krajicek",
    "Michael Jordan", "LeBron James", "Kobe Bryant", "Magic Johnson", "Larry Bird",
    "Shaquille O'Neal", "Stephen Curry", "Kevin Durant", "Giannis Antetokounmpo", "Dirk Nowitzki",
    "Tiger Woods", "Jack Nicklaus", "Rory McIlroy", "Annika Sörenstam", "Joost Luiten",
    "Usain Bolt", "Carl Lewis", "Mo Farah", "Eliud Kipchoge", "Fanny Blankers-Koen",
    "Dafne Schippers", "Sifan Hassan", "Femke Bol", "Nelli Cooman", "Ria Stalman",
    "Pieter van den Hoogenband", "Inge de Bruijn", "Ranomi Kromowidjojo", "Marleen Veldhuis", "Ireen Wüst",
    "Sven Kramer", "Jorrit Bergsma", "Kjeld Nuis", "Jutta Leerdam", "Irene Schouten",
    "Ard Schenk", "Kees Verkerk", "Yvonne van Gennip", "Marianne Timmer", "Anni Friesinger",
    "Epke Zonderland", "Sanne Wevers", "Maxime Verhagen", "Esther Vergeer", "Diede de Groot",
    "Tom Dumoulin", "Mathieu van der Poel", "Wout van Aert", "Marianne Vos", "Anna van der Breggen",
    "Leontien van Moorsel", "Erik Dekker", "Joop Zoetemelk", "Jan Janssen", "Peter Post",
    "AFC Ajax", "De Kuip", "Johan Cruijff ArenA", "Philips Stadion", "Cars Jeans Stadion",
    "offside", "penalty", "corner kick", "free kick", "own goal",
    "hat-trick", "red card", "yellow card", " VAR", "goalkeeper",
    "striker", "midfielder", "defender", "captain", "manager",
    "knockout", "uppercut", "jab", "slam dunk", "three-pointer",
    "home run", "touchdown", "ace", "deuce", "break point",
    "birdie", "eagle", "hole in one", "albatross", "par",
    "photo finish", "world record", "personal best", "gold medal", "silver medal",
    "bronze medal", "podium", "lap of honour", "mascot", "opening ceremony",
    "torch", "stadium", "arena", "pitch", "court",
    "rink", "pool", "track", "velodrome", "piste",
    "coach", "referee", "umpire", "linesman", "steward",
    "fan", "ultras", "derby", "clásico", "play-off",
    "relegation", "promotion", "transfer", "loan", "free agent",
    "KNVB", "FIFA", "UEFA", "IOC", "FIFA World Cup",
    "Davis Cup", "Ryder Cup", "America's Cup", "Rugby World Cup", "Cricket World Cup",
    "NBA", "NFL", "MLB", "NHL", "PGA Tour",
    "Formule 1", "MotoGP", "Dakar Rally", "Le Mans", "Indy 500",
    "Elfstedentocht", "Vierdaagse", "Amsterdam Marathon", "Rotterdam Marathon", "Alpe d'HuZes",
    "Hockey World Cup", "FIH Pro League", "Orange Lions", "Orange Women", "Oranje",
    "keirin", "madison", "omnium", "pursuit", "time trial",
    "butterfly", "backstroke", "breaststroke", "freestyle", "medley",
    "halfpipe", "slalom", "downhill", "super-G", "moguls",
    "sumo", "kabaddi", "sepak takraw", "petanque", "korfbal",
    "Honkbal", "softbal", "beachvolleybal", "zaalvoetbal", "waterpolo",
])

DUTCH_CULTURE = unique([
    "Sinterklaas", "Zwarte Piet", "pakjesavond", "schoen zetten", "strooigoed",
    "pepernoten", "kruidnoten", "chocoladeletter", "taaitaai", "speculaaspop",
    "Sint Nicolaas", "stoomboot", "Spanje", "Madrid", "Pietenpiet",
    "Sinterklaasjournaal", "Het Klokhuis", "Jeugdjournaal", "Schooltv", "Willem Wever",
    "Koningsdag", "oranje", "vrijmarkt", "koningsnacht", "oranjebitter",
    "Bevrijdingsdag", "Dodenherdenking", "twee minuten stilte", "Prinsjesdag", "troonrede",
    "koffer", "gouden koets", "hoedjesparade", "Miljoenennota", "Algemene Politieke Beschouwingen",
    "Eerste Kamer", "Tweede Kamer", "Binnenhof", "Torentje", "Catshuis",
    "polderen", "overleg", "maakbaarheid", "gedogen", "gedoogsteun",
    "verzuiling", "CDA", "PvdA", "VVD", "D66",
    "GroenLinks", "SP", "PVV", "BBB", "NSC",
    "Partij voor de Dieren", "Forum voor Democratie", "ChristenUnie", "SGP", "Volt",
    "Mark Rutte", "Dick Schoof", "Geert Wilders", "Frans Timmermans", "Jesse Klaver",
    "Lilian Marijnissen", "Caroline van der Plas", "Pieter Omtzigt", "Rob Jetten", "Dilan Yeşilgöz",
    "Wopke Hoekstra", "Sigrid Kaag", "Hugo de Jonge", "Ernst Kuipers", "Ferd Grapperhaus",
    "Willem-Alexander", "Máxima", "Amalia", "Alexia", "Ariane",
    "prins Constantijn", "prinses Laurentien", "Beatrix", "Juliana", "Wilhelmina",
    "prins Bernhard", "prins Claus", "Emma", "Willem I", "Willem van Oranje",
    "Tachtigjarige Oorlog", "Watergeuzen", "Alva", "Filips II", "Unie van Utrecht",
    "Vrede van Münster", "Gouden Eeuw", "VOC", "WIC", "slavernij",
    "Keti Koti", "koloniën", "Nederlands-Indië", "Suriname", "Antillen",
    "Curaçao", "Aruba", "Sint Maarten", "Bonaire", "Saba",
    "Sint Eustatius", "Indiëgangers", "politionele acties", "Molukkers", "gastarbeiders",
    "polder", "droogmakerij", "Beemster", "Schermer", "Haarlemmermeer",
    "Afsluitdijk", "Zuiderzee", "IJsselmeer", "Flevoland", "Lelystad",
    "Deltawerken", "Oosterscheldekering", "Maeslantkering", "Waterschap", "dijkgraaf",
    "klompen", "tulpen", "hyacint", "narcis", "bollenteelt",
    "Keukenhof", "bollenstreek", "Lisse", "Hillegom", "Noordwijk",
    "kaasmarkt", "Alkmaar", "Gouda", "Edam", "Woerden",
    "stroopwafel", "drop", "zoute drop", "dubbelzout", "lakritz",
    "hagelslag", "vlokken", "muisjes", "de Ruijter", "Venz",
    "erwtensoep", "snert", "rookworst", "boerenkoolstamppot", "hutspot",
    "andijviestamppot", "zuurkoolstamppot", "hetexbliksems", "stamppot raapstelen", "worst",
    "kroket", "bitterbal", "frikandel", "kaassoufflé", "nasischijf",
    "bamischijf", "berenklauw", "sateh", "patat speciaal", "patatje oorlog",
    "haring", "Hollandse nieuwe", "uitjes", "zuur", "kibbeling",
    "oliebol", "appelflap", "tompouce", "oranje tompouce", "gevulde koek",
    "eierkoek", "ontbijtkoek", "peperkoek", "stroopkoek", "roze koek",
    "jenever", "oude jenever", "jonge jenever", "advocaat", "oranjebitter",
    "beerenburg", "bittertje", "sneeuwbal", "schrobbeler", "els",
    "bruin café", "proeflokaal", "borrel", "borrelhapje", "bittergarnituur",
    "Elfstedentocht", "tocht der tochten", "klunen", "puntgaaf", "barrevoeters",
    "Lee uwarden", "Sneek", "IJlst", "Sloten", "Stavoren",
    "Hindeloopen", "Workum", "Bolsward", "Harlingen", "Dokkum",
    "Franeker", "Friesland", "skûtsjesilen", "kaatsen", "fierljeppen",
    "nagelbijten", "klootschieten", "carbidschieten", "oudejaarsdag", "nieuwjaarsduik",
    "Scheveningen", "Nieuwjaarsduik", "oliebollenkraam", "vuurwerk", "knal",
    "kermis", "draaimolen", "botsauto's", "reuzenrad", "suikerspin",
    "smelten ijs", "poffertjeskraam", "oliebollen", "wafel", "slagroom",
    "Efteling", "Sprookjesbos", "Droomvlucht", "Python", "Baron 1898",
    "Villa Volta", "Fata Morgana", "Symbolica", "Joris en de Draak", "De Vliegende Hollander",
    "Madurodam", "Duinrell", "Slagharen", "Walibi", "Toverland",
    "Burgers' Zoo", "Ouwehands", "Blijdorp", "Artis", "Apenheul",
    "Nijntje", "Dick Bruna", "Miffy", "Kikker", "Dikkie Dik",
    "Jip en Janneke", "Annie M.G. Schmidt", "Pluk van de Petteflet", "Otje", "Abeltje",
    "Kruistocht in spijkerbroek", "Koning van Katoren", "Oorlogswinter", "Het Achterhuis", "Max Havelaar",
    "Multatuli", "Harry Mulisch", "Gerard Reve", "Willem Frederik Hermans", "Cees Nooteboom",
    "Tommy Wieringa", "Herman Koch", "Connie Palmen", "Renate Dorrestein", "Nescio",
    "Van Kooten en De Bie", "Freek de Jonge", "Youp van 't Hek", "Theo Maassen", "Jochem Myjer",
    "Claudia de Breij", "Najik Amhali", "Roué Verveer", "Soundos El Ahmadi", "Jandino",
    "Paul de Leeuw", "André van Duin", "Tineke Schouten", "Irene Moors", "Carlo Boszhard",
    "Chantal Janzen", "Linda de Mol", "Wendy van Dijk", "Bridget Maasland", "Patty Brard",
    "Gordon", "Gérard Joling", "René Froger", "Lee Towers", "Lee Towers",
    "Guus Meeuwis", "Acda en De Munnik", "BLØF", "Doe Maar", "Het Goede Doel",
    "Kinderdijk", "Zaanse Schans", "Giethoorn", "Marken", "Volendam",
    "Urk", "Staphorst", "Spakenburg", "Bunschoten", "Scheveningen haven",
    "grachtenpand", "trapgevel", "klokgevel", "hofje", "begijnhof",
    "molen", "poldermolen", "stellingmolen", "watermolen", "zaagmolen",
    "fiets", "oma fiets", "bakfiets", "ov-fiets", "fietspad",
    "voorrang", "rotonde", "stoep", "tegeltjeswijsheid", "nuchter",
    "doe maar gewoon", "kalm aan", "gezellig", "uitwaaien", "aanmodderen",
    "jammer maar helaas", "daar ga je", "hup Holland hup", "oranjegekte", "wimpel",
    "vlag", "rood-wit-blauw", "statenvlag", "prinsenvlag", "leeuw",
    "Nederlandse leeuw", "Hollandse meester", "Nachtwacht", "Melkmeisje", "Zonnebloemen",
    "Rijksmuseum", "Mauritshuis", "Kröller-Müller", "Boijmans", "Stedelijk",
    "Vincent van Gogh", "Rembrandt van Rijn", "Johannes Vermeer", "Frans Hals", "Jan Steen",
    "Piet Mondriaan", "Karel Appel", "CoBrA", "Escher", "MC Escher",
    "Drop", "Dropshot", "winegum", "zoute haring", "nieuwe haring",
    "beschuit met muisjes", "kraamzorg", "consultatiebureau", "inburgering", "inburgeringsexamen",
    "DigiD", "toeslagen", "zorgverzekering", "eigen risico", "huisarts",
    "apotheek", "tandarts", "fysiotherapeut", "GGD", "RIVM",
    "NS", "sprinter", "intercity", "ov-chipkaart", "check-in",
    "OV", "bus", "tram", "metro", "waterbus",
    "pont", "fietsenstalling", "fietssleutel", "slot", "ommetje",
    "borrelnootjes", "kaasstengels", "tostie", "uitsmijter", "uitsmijter spek",
    "kroketten uit de muur", "Febo", "HEMA rookworst", "AH bonus", "stempelkaart",
])


def emit(pack_id, lang, words, mixed=False):
    words = unique(words)
    print(f"{pack_id}: {len(words)} words")
    lines = [
        f"const PACK = {pack_id!r};",
        "export const WORDS = [",
    ]
    for w in words:
        # movies/music/sports mix NL+EN — lang is a default; we don't split
        L = lang
        lines.append(f"  {{ text: {w!r}, lang: {L!r}, pack: PACK }},")
    lines.append("];")
    lines.append("")
    (OUT / f"{pack_id}.js").write_text("\n".join(lines), encoding="utf-8")
    return {(w.casefold(), pack_id) for w in words}, words


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    all_keys = {}
    for pack_id, lang, words in [
        ("nl_general", "nl", NL_GENERAL),
        ("en_general", "en", EN_GENERAL),
        ("movies", "mix", MOVIES),
        ("music", "mix", MUSIC),
        ("sports", "mix", SPORTS),
        ("dutch_culture", "nl", DUTCH_CULTURE),
    ]:
        keys, words = emit(pack_id, lang, words)
        for w in words:
            k = w.casefold()
            if k in all_keys and all_keys[k] != pack_id:
                # allow cross-pack repeats; dealCard de-dupes by text
                pass
            all_keys[k] = pack_id
    print("done")


if __name__ == "__main__":
    main()
