const PACK = 'en_general';
export const WORDS = [
  { text: 'Albert Einstein', lang: 'en', pack: PACK },
  { text: 'Isaac Newton', lang: 'en', pack: PACK },
  { text: 'Charles Darwin', lang: 'en', pack: PACK },
  { text: 'Marie Curie', lang: 'en', pack: PACK },
  { text: 'Stephen Hawking', lang: 'en', pack: PACK },
  { text: 'Leonardo da Vinci', lang: 'en', pack: PACK },
  { text: 'Michelangelo', lang: 'en', pack: PACK },
  { text: 'Picasso', lang: 'en', pack: PACK },
  { text: 'Frida Kahlo', lang: 'en', pack: PACK },
  { text: 'Andy Warhol', lang: 'en', pack: PACK },
  { text: 'Shakespeare', lang: 'en', pack: PACK },
  { text: 'Charles Dickens', lang: 'en', pack: PACK },
  { text: 'Jane Austen', lang: 'en', pack: PACK },
  { text: 'J.K. Rowling', lang: 'en', pack: PACK },
  { text: 'Tolkien', lang: 'en', pack: PACK },
  { text: 'Winston Churchill', lang: 'en', pack: PACK },
  { text: 'Abraham Lincoln', lang: 'en', pack: PACK },
  { text: 'Nelson Mandela', lang: 'en', pack: PACK },
  { text: 'Mahatma Gandhi', lang: 'en', pack: PACK },
  { text: 'Martin Luther King', lang: 'en', pack: PACK },
  { text: 'Barack Obama', lang: 'en', pack: PACK },
  { text: 'Donald Trump', lang: 'en', pack: PACK },
  { text: 'Joe Biden', lang: 'en', pack: PACK },
  { text: 'Angela Merkel', lang: 'en', pack: PACK },
  { text: 'Vladimir Putin', lang: 'en', pack: PACK },
  { text: 'Queen Elizabeth', lang: 'en', pack: PACK },
  { text: 'King Charles', lang: 'en', pack: PACK },
  { text: 'Princess Diana', lang: 'en', pack: PACK },
  { text: 'Prince Harry', lang: 'en', pack: PACK },
  { text: 'Meghan Markle', lang: 'en', pack: PACK },
  { text: 'The Pope', lang: 'en', pack: PACK },
  { text: 'Dalai Lama', lang: 'en', pack: PACK },
  { text: 'Oprah Winfrey', lang: 'en', pack: PACK },
  { text: 'Ellen DeGeneres', lang: 'en', pack: PACK },
  { text: 'David Attenborough', lang: 'en', pack: PACK },
  { text: 'Gordon Ramsay', lang: 'en', pack: PACK },
  { text: 'Jamie Oliver', lang: 'en', pack: PACK },
  { text: 'Martha Stewart', lang: 'en', pack: PACK },
  { text: 'Julia Child', lang: 'en', pack: PACK },
  { text: 'Anthony Bourdain', lang: 'en', pack: PACK },
  { text: 'Elon Musk', lang: 'en', pack: PACK },
  { text: 'Jeff Bezos', lang: 'en', pack: PACK },
  { text: 'Bill Gates', lang: 'en', pack: PACK },
  { text: 'Steve Jobs', lang: 'en', pack: PACK },
  { text: 'Mark Zuckerberg', lang: 'en', pack: PACK },
  { text: 'Taylor Swift', lang: 'en', pack: PACK },
  { text: 'Beyoncé', lang: 'en', pack: PACK },
  { text: 'Rihanna', lang: 'en', pack: PACK },
  { text: 'Lady Gaga', lang: 'en', pack: PACK },
  { text: 'Adele', lang: 'en', pack: PACK },
  { text: 'Ed Sheeran', lang: 'en', pack: PACK },
  { text: 'Bruno Mars', lang: 'en', pack: PACK },
  { text: 'The Weeknd', lang: 'en', pack: PACK },
  { text: 'Drake', lang: 'en', pack: PACK },
  { text: 'Kanye West', lang: 'en', pack: PACK },
  { text: 'Michael Jackson', lang: 'en', pack: PACK },
  { text: 'Elvis Presley', lang: 'en', pack: PACK },
  { text: 'Madonna', lang: 'en', pack: PACK },
  { text: 'Prince', lang: 'en', pack: PACK },
  { text: 'David Bowie', lang: 'en', pack: PACK },
  { text: 'The Beatles', lang: 'en', pack: PACK },
  { text: 'The Rolling Stones', lang: 'en', pack: PACK },
  { text: 'Queen', lang: 'en', pack: PACK },
  { text: 'ABBA', lang: 'en', pack: PACK },
  { text: 'U2', lang: 'en', pack: PACK },
  { text: 'Tom Cruise', lang: 'en', pack: PACK },
  { text: 'Brad Pitt', lang: 'en', pack: PACK },
  { text: 'Leonardo DiCaprio', lang: 'en', pack: PACK },
  { text: 'Johnny Depp', lang: 'en', pack: PACK },
  { text: 'Will Smith', lang: 'en', pack: PACK },
  { text: 'Denzel Washington', lang: 'en', pack: PACK },
  { text: 'Tom Hanks', lang: 'en', pack: PACK },
  { text: 'Morgan Freeman', lang: 'en', pack: PACK },
  { text: 'Robert De Niro', lang: 'en', pack: PACK },
  { text: 'Al Pacino', lang: 'en', pack: PACK },
  { text: 'Meryl Streep', lang: 'en', pack: PACK },
  { text: 'Scarlett Johansson', lang: 'en', pack: PACK },
  { text: 'Jennifer Lawrence', lang: 'en', pack: PACK },
  { text: 'Natalie Portman', lang: 'en', pack: PACK },
  { text: 'Emma Stone', lang: 'en', pack: PACK },
  { text: 'Angelina Jolie', lang: 'en', pack: PACK },
  { text: 'Nicole Kidman', lang: 'en', pack: PACK },
  { text: 'Charlize Theron', lang: 'en', pack: PACK },
  { text: 'Sandra Bullock', lang: 'en', pack: PACK },
  { text: 'Julia Roberts', lang: 'en', pack: PACK },
  { text: 'Keanu Reeves', lang: 'en', pack: PACK },
  { text: 'Chris Hemsworth', lang: 'en', pack: PACK },
  { text: 'Chris Evans', lang: 'en', pack: PACK },
  { text: 'Robert Downey Jr.', lang: 'en', pack: PACK },
  { text: 'Hugh Jackman', lang: 'en', pack: PACK },
  { text: 'London', lang: 'en', pack: PACK },
  { text: 'Paris', lang: 'en', pack: PACK },
  { text: 'New York', lang: 'en', pack: PACK },
  { text: 'Los Angeles', lang: 'en', pack: PACK },
  { text: 'Tokyo', lang: 'en', pack: PACK },
  { text: 'Rome', lang: 'en', pack: PACK },
  { text: 'Berlin', lang: 'en', pack: PACK },
  { text: 'Madrid', lang: 'en', pack: PACK },
  { text: 'Barcelona', lang: 'en', pack: PACK },
  { text: 'Lisbon', lang: 'en', pack: PACK },
  { text: 'Athens', lang: 'en', pack: PACK },
  { text: 'Cairo', lang: 'en', pack: PACK },
  { text: 'Dubai', lang: 'en', pack: PACK },
  { text: 'Sydney', lang: 'en', pack: PACK },
  { text: 'Melbourne', lang: 'en', pack: PACK },
  { text: 'Toronto', lang: 'en', pack: PACK },
  { text: 'Vancouver', lang: 'en', pack: PACK },
  { text: 'Chicago', lang: 'en', pack: PACK },
  { text: 'San Francisco', lang: 'en', pack: PACK },
  { text: 'Miami', lang: 'en', pack: PACK },
  { text: 'Las Vegas', lang: 'en', pack: PACK },
  { text: 'Hawaii', lang: 'en', pack: PACK },
  { text: 'Iceland', lang: 'en', pack: PACK },
  { text: 'Norway', lang: 'en', pack: PACK },
  { text: 'Sweden', lang: 'en', pack: PACK },
  { text: 'Finland', lang: 'en', pack: PACK },
  { text: 'Denmark', lang: 'en', pack: PACK },
  { text: 'Ireland', lang: 'en', pack: PACK },
  { text: 'Scotland', lang: 'en', pack: PACK },
  { text: 'Wales', lang: 'en', pack: PACK },
  { text: 'England', lang: 'en', pack: PACK },
  { text: 'Canada', lang: 'en', pack: PACK },
  { text: 'United States', lang: 'en', pack: PACK },
  { text: 'Mexico', lang: 'en', pack: PACK },
  { text: 'Brazil', lang: 'en', pack: PACK },
  { text: 'Argentina', lang: 'en', pack: PACK },
  { text: 'Chile', lang: 'en', pack: PACK },
  { text: 'Peru', lang: 'en', pack: PACK },
  { text: 'Colombia', lang: 'en', pack: PACK },
  { text: 'South Africa', lang: 'en', pack: PACK },
  { text: 'Kenya', lang: 'en', pack: PACK },
  { text: 'Egypt', lang: 'en', pack: PACK },
  { text: 'Morocco', lang: 'en', pack: PACK },
  { text: 'India', lang: 'en', pack: PACK },
  { text: 'China', lang: 'en', pack: PACK },
  { text: 'Japan', lang: 'en', pack: PACK },
  { text: 'South Korea', lang: 'en', pack: PACK },
  { text: 'Thailand', lang: 'en', pack: PACK },
  { text: 'Vietnam', lang: 'en', pack: PACK },
  { text: 'Indonesia', lang: 'en', pack: PACK },
  { text: 'Australia', lang: 'en', pack: PACK },
  { text: 'New Zealand', lang: 'en', pack: PACK },
  { text: 'Antarctica', lang: 'en', pack: PACK },
  { text: 'Sahara', lang: 'en', pack: PACK },
  { text: 'Amazon rainforest', lang: 'en', pack: PACK },
  { text: 'Mount Everest', lang: 'en', pack: PACK },
  { text: 'Grand Canyon', lang: 'en', pack: PACK },
  { text: 'Niagara Falls', lang: 'en', pack: PACK },
  { text: 'Statue of Liberty', lang: 'en', pack: PACK },
  { text: 'Eiffel Tower', lang: 'en', pack: PACK },
  { text: 'Big Ben', lang: 'en', pack: PACK },
  { text: 'Tower Bridge', lang: 'en', pack: PACK },
  { text: 'Colosseum', lang: 'en', pack: PACK },
  { text: 'Acropolis', lang: 'en', pack: PACK },
  { text: 'Pyramids of Giza', lang: 'en', pack: PACK },
  { text: 'Great Wall of China', lang: 'en', pack: PACK },
  { text: 'Taj Mahal', lang: 'en', pack: PACK },
  { text: 'Machu Picchu', lang: 'en', pack: PACK },
  { text: 'Christ the Redeemer', lang: 'en', pack: PACK },
  { text: 'Sydney Opera House', lang: 'en', pack: PACK },
  { text: 'Golden Gate Bridge', lang: 'en', pack: PACK },
  { text: 'Times Square', lang: 'en', pack: PACK },
  { text: 'Hollywood', lang: 'en', pack: PACK },
  { text: 'Broadway', lang: 'en', pack: PACK },
  { text: 'Wall Street', lang: 'en', pack: PACK },
  { text: 'White House', lang: 'en', pack: PACK },
  { text: 'Buckingham Palace', lang: 'en', pack: PACK },
  { text: 'Tower of London', lang: 'en', pack: PACK },
  { text: 'Stonehenge', lang: 'en', pack: PACK },
  { text: 'Loch Ness', lang: 'en', pack: PACK },
  { text: 'coffee', lang: 'en', pack: PACK },
  { text: 'tea', lang: 'en', pack: PACK },
  { text: 'pizza', lang: 'en', pack: PACK },
  { text: 'hamburger', lang: 'en', pack: PACK },
  { text: 'hot dog', lang: 'en', pack: PACK },
  { text: 'sushi', lang: 'en', pack: PACK },
  { text: 'taco', lang: 'en', pack: PACK },
  { text: 'burrito', lang: 'en', pack: PACK },
  { text: 'spaghetti', lang: 'en', pack: PACK },
  { text: 'lasagna', lang: 'en', pack: PACK },
  { text: 'pancake', lang: 'en', pack: PACK },
  { text: 'waffle', lang: 'en', pack: PACK },
  { text: 'doughnut', lang: 'en', pack: PACK },
  { text: 'cupcake', lang: 'en', pack: PACK },
  { text: 'ice cream', lang: 'en', pack: PACK },
  { text: 'chocolate', lang: 'en', pack: PACK },
  { text: 'popcorn', lang: 'en', pack: PACK },
  { text: 'pretzel', lang: 'en', pack: PACK },
  { text: 'bagel', lang: 'en', pack: PACK },
  { text: 'sandwich', lang: 'en', pack: PACK },
  { text: 'ketchup', lang: 'en', pack: PACK },
  { text: 'mustard', lang: 'en', pack: PACK },
  { text: 'mayonnaise', lang: 'en', pack: PACK },
  { text: 'barbecue', lang: 'en', pack: PACK },
  { text: 'breakfast', lang: 'en', pack: PACK },
  { text: 'umbrella', lang: 'en', pack: PACK },
  { text: 'backpack', lang: 'en', pack: PACK },
  { text: 'suitcase', lang: 'en', pack: PACK },
  { text: 'passport', lang: 'en', pack: PACK },
  { text: 'camera', lang: 'en', pack: PACK },
  { text: 'smartphone', lang: 'en', pack: PACK },
  { text: 'laptop', lang: 'en', pack: PACK },
  { text: 'headphones', lang: 'en', pack: PACK },
  { text: 'remote control', lang: 'en', pack: PACK },
  { text: 'microwave', lang: 'en', pack: PACK },
  { text: 'refrigerator', lang: 'en', pack: PACK },
  { text: 'toaster', lang: 'en', pack: PACK },
  { text: 'blender', lang: 'en', pack: PACK },
  { text: 'vacuum cleaner', lang: 'en', pack: PACK },
  { text: 'washing machine', lang: 'en', pack: PACK },
  { text: 'toothbrush', lang: 'en', pack: PACK },
  { text: 'shampoo', lang: 'en', pack: PACK },
  { text: 'soap', lang: 'en', pack: PACK },
  { text: 'towel', lang: 'en', pack: PACK },
  { text: 'pillow', lang: 'en', pack: PACK },
  { text: 'alarm clock', lang: 'en', pack: PACK },
  { text: 'calendar', lang: 'en', pack: PACK },
  { text: 'dictionary', lang: 'en', pack: PACK },
  { text: 'newspaper', lang: 'en', pack: PACK },
  { text: 'magazine', lang: 'en', pack: PACK },
  { text: 'library', lang: 'en', pack: PACK },
  { text: 'museum', lang: 'en', pack: PACK },
  { text: 'airport', lang: 'en', pack: PACK },
  { text: 'train station', lang: 'en', pack: PACK },
  { text: 'subway', lang: 'en', pack: PACK },
  { text: 'taxi', lang: 'en', pack: PACK },
  { text: 'bus', lang: 'en', pack: PACK },
  { text: 'bicycle', lang: 'en', pack: PACK },
  { text: 'motorcycle', lang: 'en', pack: PACK },
  { text: 'helicopter', lang: 'en', pack: PACK },
  { text: 'submarine', lang: 'en', pack: PACK },
  { text: 'yacht', lang: 'en', pack: PACK },
  { text: 'cruise ship', lang: 'en', pack: PACK },
  { text: 'hot air balloon', lang: 'en', pack: PACK },
  { text: 'parachute', lang: 'en', pack: PACK },
  { text: 'firefighter', lang: 'en', pack: PACK },
  { text: 'police officer', lang: 'en', pack: PACK },
  { text: 'doctor', lang: 'en', pack: PACK },
  { text: 'nurse', lang: 'en', pack: PACK },
  { text: 'teacher', lang: 'en', pack: PACK },
  { text: 'pilot', lang: 'en', pack: PACK },
  { text: 'astronaut', lang: 'en', pack: PACK },
  { text: 'chef', lang: 'en', pack: PACK },
  { text: 'waiter', lang: 'en', pack: PACK },
  { text: 'farmer', lang: 'en', pack: PACK },
  { text: 'lawyer', lang: 'en', pack: PACK },
  { text: 'judge', lang: 'en', pack: PACK },
  { text: 'detective', lang: 'en', pack: PACK },
  { text: 'spy', lang: 'en', pack: PACK },
  { text: 'pirate', lang: 'en', pack: PACK },
  { text: 'knight', lang: 'en', pack: PACK },
  { text: 'princess', lang: 'en', pack: PACK },
  { text: 'wizard', lang: 'en', pack: PACK },
  { text: 'vampire', lang: 'en', pack: PACK },
  { text: 'zombie', lang: 'en', pack: PACK },
  { text: 'robot', lang: 'en', pack: PACK },
  { text: 'dinosaur', lang: 'en', pack: PACK },
  { text: 'unicorn', lang: 'en', pack: PACK },
  { text: 'dragon', lang: 'en', pack: PACK },
  { text: 'mermaid', lang: 'en', pack: PACK },
  { text: 'elephant', lang: 'en', pack: PACK },
  { text: 'giraffe', lang: 'en', pack: PACK },
  { text: 'penguin', lang: 'en', pack: PACK },
  { text: 'kangaroo', lang: 'en', pack: PACK },
  { text: 'koala', lang: 'en', pack: PACK },
  { text: 'dolphin', lang: 'en', pack: PACK },
  { text: 'whale', lang: 'en', pack: PACK },
  { text: 'shark', lang: 'en', pack: PACK },
  { text: 'octopus', lang: 'en', pack: PACK },
  { text: 'jellyfish', lang: 'en', pack: PACK },
  { text: 'eagle', lang: 'en', pack: PACK },
  { text: 'owl', lang: 'en', pack: PACK },
  { text: 'peacock', lang: 'en', pack: PACK },
  { text: 'flamingo', lang: 'en', pack: PACK },
  { text: 'parrot', lang: 'en', pack: PACK },
  { text: 'lion', lang: 'en', pack: PACK },
  { text: 'tiger', lang: 'en', pack: PACK },
  { text: 'cheetah', lang: 'en', pack: PACK },
  { text: 'wolf', lang: 'en', pack: PACK },
  { text: 'fox', lang: 'en', pack: PACK },
  { text: 'bear', lang: 'en', pack: PACK },
  { text: 'panda', lang: 'en', pack: PACK },
  { text: 'sloth', lang: 'en', pack: PACK },
  { text: 'hedgehog', lang: 'en', pack: PACK },
  { text: 'squirrel', lang: 'en', pack: PACK },
  { text: 'rainbow', lang: 'en', pack: PACK },
  { text: 'thunderstorm', lang: 'en', pack: PACK },
  { text: 'earthquake', lang: 'en', pack: PACK },
  { text: 'volcano', lang: 'en', pack: PACK },
  { text: 'avalanche', lang: 'en', pack: PACK },
  { text: 'desert', lang: 'en', pack: PACK },
  { text: 'jungle', lang: 'en', pack: PACK },
  { text: 'glacier', lang: 'en', pack: PACK },
  { text: 'waterfall', lang: 'en', pack: PACK },
  { text: 'island', lang: 'en', pack: PACK },
  { text: 'compass', lang: 'en', pack: PACK },
  { text: 'telescope', lang: 'en', pack: PACK },
  { text: 'microscope', lang: 'en', pack: PACK },
  { text: 'magnet', lang: 'en', pack: PACK },
  { text: 'battery', lang: 'en', pack: PACK },
  { text: 'lightbulb', lang: 'en', pack: PACK },
  { text: 'candle', lang: 'en', pack: PACK },
  { text: 'matchstick', lang: 'en', pack: PACK },
  { text: 'flashlight', lang: 'en', pack: PACK },
  { text: 'lantern', lang: 'en', pack: PACK },
  { text: 'scissors', lang: 'en', pack: PACK },
  { text: 'hammer', lang: 'en', pack: PACK },
  { text: 'screwdriver', lang: 'en', pack: PACK },
  { text: 'wrench', lang: 'en', pack: PACK },
  { text: 'needle', lang: 'en', pack: PACK },
  { text: 'button', lang: 'en', pack: PACK },
  { text: 'zipper', lang: 'en', pack: PACK },
  { text: 'pocket', lang: 'en', pack: PACK },
  { text: 'sleeve', lang: 'en', pack: PACK },
  { text: 'collar', lang: 'en', pack: PACK },
  { text: 'Monday', lang: 'en', pack: PACK },
  { text: 'Friday', lang: 'en', pack: PACK },
  { text: 'weekend', lang: 'en', pack: PACK },
  { text: 'midnight', lang: 'en', pack: PACK },
  { text: 'sunrise', lang: 'en', pack: PACK },
  { text: 'Christmas', lang: 'en', pack: PACK },
  { text: 'Halloween', lang: 'en', pack: PACK },
  { text: 'Thanksgiving', lang: 'en', pack: PACK },
  { text: "Valentine's Day", lang: 'en', pack: PACK },
  { text: "New Year's Eve", lang: 'en', pack: PACK },
  { text: 'Olympics', lang: 'en', pack: PACK },
  { text: 'World Cup', lang: 'en', pack: PACK },
  { text: 'Super Bowl', lang: 'en', pack: PACK },
  { text: 'Wimbledon', lang: 'en', pack: PACK },
  { text: 'Tour de France', lang: 'en', pack: PACK },
  { text: 'Google', lang: 'en', pack: PACK },
  { text: 'Apple', lang: 'en', pack: PACK },
  { text: 'Microsoft', lang: 'en', pack: PACK },
  { text: 'Amazon', lang: 'en', pack: PACK },
  { text: 'Netflix', lang: 'en', pack: PACK },
  { text: 'YouTube', lang: 'en', pack: PACK },
  { text: 'Instagram', lang: 'en', pack: PACK },
  { text: 'TikTok', lang: 'en', pack: PACK },
  { text: 'WhatsApp', lang: 'en', pack: PACK },
  { text: 'Spotify', lang: 'en', pack: PACK },
  { text: "McDonald's", lang: 'en', pack: PACK },
  { text: 'Starbucks', lang: 'en', pack: PACK },
  { text: 'Coca-Cola', lang: 'en', pack: PACK },
  { text: 'Pepsi', lang: 'en', pack: PACK },
  { text: 'Ikea', lang: 'en', pack: PACK },
  { text: 'Lego', lang: 'en', pack: PACK },
  { text: 'Barbie', lang: 'en', pack: PACK },
  { text: 'PlayStation', lang: 'en', pack: PACK },
  { text: 'Nintendo', lang: 'en', pack: PACK },
  { text: 'Xbox', lang: 'en', pack: PACK },
  { text: 'Harry Potter', lang: 'en', pack: PACK },
  { text: 'Sherlock Holmes', lang: 'en', pack: PACK },
  { text: 'James Bond', lang: 'en', pack: PACK },
  { text: 'Superman', lang: 'en', pack: PACK },
  { text: 'Batman', lang: 'en', pack: PACK },
  { text: 'Spider-Man', lang: 'en', pack: PACK },
  { text: 'Wonder Woman', lang: 'en', pack: PACK },
  { text: 'Iron Man', lang: 'en', pack: PACK },
  { text: 'Hulk', lang: 'en', pack: PACK },
  { text: 'Thor', lang: 'en', pack: PACK },
  { text: 'Mickey Mouse', lang: 'en', pack: PACK },
  { text: 'Donald Duck', lang: 'en', pack: PACK },
  { text: 'Winnie the Pooh', lang: 'en', pack: PACK },
  { text: 'SpongeBob', lang: 'en', pack: PACK },
  { text: 'Pikachu', lang: 'en', pack: PACK },
  { text: 'Mario', lang: 'en', pack: PACK },
  { text: 'Sonic', lang: 'en', pack: PACK },
  { text: 'Link', lang: 'en', pack: PACK },
  { text: 'Master Chief', lang: 'en', pack: PACK },
  { text: 'Lara Croft', lang: 'en', pack: PACK },
];
