const PACK = 'movies';
export const WORDS = [
  { text: 'Titanic', lang: 'mix', pack: PACK },
  { text: 'Avatar', lang: 'mix', pack: PACK },
  { text: 'The Godfather', lang: 'mix', pack: PACK },
  { text: 'Pulp Fiction', lang: 'mix', pack: PACK },
  { text: 'Forrest Gump', lang: 'mix', pack: PACK },
  { text: 'The Shawshank Redemption', lang: 'mix', pack: PACK },
  { text: 'The Dark Knight', lang: 'mix', pack: PACK },
  { text: 'Inception', lang: 'mix', pack: PACK },
  { text: 'Interstellar', lang: 'mix', pack: PACK },
  { text: 'The Matrix', lang: 'mix', pack: PACK },
  { text: 'Jurassic Park', lang: 'mix', pack: PACK },
  { text: 'Jaws', lang: 'mix', pack: PACK },
  { text: 'E.T.', lang: 'mix', pack: PACK },
  { text: 'Star Wars', lang: 'mix', pack: PACK },
  { text: 'The Empire Strikes Back', lang: 'mix', pack: PACK },
  { text: 'Return of the Jedi', lang: 'mix', pack: PACK },
  { text: 'The Force Awakens', lang: 'mix', pack: PACK },
  { text: 'The Phantom Menace', lang: 'mix', pack: PACK },
  { text: 'Raiders of the Lost Ark', lang: 'mix', pack: PACK },
  { text: 'Indiana Jones', lang: 'mix', pack: PACK },
  { text: 'Back to the Future', lang: 'mix', pack: PACK },
  { text: 'Ghostbusters', lang: 'mix', pack: PACK },
  { text: 'Gremlins', lang: 'mix', pack: PACK },
  { text: 'The Goonies', lang: 'mix', pack: PACK },
  { text: 'Home Alone', lang: 'mix', pack: PACK },
  { text: 'Die Hard', lang: 'mix', pack: PACK },
  { text: 'Terminator', lang: 'mix', pack: PACK },
  { text: 'Terminator 2', lang: 'mix', pack: PACK },
  { text: 'Alien', lang: 'mix', pack: PACK },
  { text: 'Aliens', lang: 'mix', pack: PACK },
  { text: 'Predator', lang: 'mix', pack: PACK },
  { text: 'RoboCop', lang: 'mix', pack: PACK },
  { text: 'Total Recall', lang: 'mix', pack: PACK },
  { text: 'Blade Runner', lang: 'mix', pack: PACK },
  { text: 'Mad Max', lang: 'mix', pack: PACK },
  { text: 'The Lord of the Rings', lang: 'mix', pack: PACK },
  { text: 'The Fellowship of the Ring', lang: 'mix', pack: PACK },
  { text: 'The Two Towers', lang: 'mix', pack: PACK },
  { text: 'The Return of the King', lang: 'mix', pack: PACK },
  { text: 'The Hobbit', lang: 'mix', pack: PACK },
  { text: "Harry Potter and the Philosopher's Stone", lang: 'mix', pack: PACK },
  { text: 'Harry Potter and the Chamber of Secrets', lang: 'mix', pack: PACK },
  { text: 'Harry Potter and the Prisoner of Azkaban', lang: 'mix', pack: PACK },
  { text: 'Harry Potter and the Goblet of Fire', lang: 'mix', pack: PACK },
  { text: 'Harry Potter and the Deathly Hallows', lang: 'mix', pack: PACK },
  { text: 'The Hunger Games', lang: 'mix', pack: PACK },
  { text: 'Twilight', lang: 'mix', pack: PACK },
  { text: 'The Fault in Our Stars', lang: 'mix', pack: PACK },
  { text: 'La La Land', lang: 'mix', pack: PACK },
  { text: 'Whiplash', lang: 'mix', pack: PACK },
  { text: 'Parasite', lang: 'mix', pack: PACK },
  { text: 'Everything Everywhere All at Once', lang: 'mix', pack: PACK },
  { text: 'Oppenheimer', lang: 'mix', pack: PACK },
  { text: 'Barbie', lang: 'mix', pack: PACK },
  { text: 'Dune', lang: 'mix', pack: PACK },
  { text: 'The Batman', lang: 'mix', pack: PACK },
  { text: 'Joker', lang: 'mix', pack: PACK },
  { text: 'Black Panther', lang: 'mix', pack: PACK },
  { text: 'Avengers: Endgame', lang: 'mix', pack: PACK },
  { text: 'Avengers: Infinity War', lang: 'mix', pack: PACK },
  { text: 'Iron Man', lang: 'mix', pack: PACK },
  { text: 'Captain America', lang: 'mix', pack: PACK },
  { text: 'Thor: Ragnarok', lang: 'mix', pack: PACK },
  { text: 'Guardians of the Galaxy', lang: 'mix', pack: PACK },
  { text: 'Doctor Strange', lang: 'mix', pack: PACK },
  { text: 'Spider-Man: No Way Home', lang: 'mix', pack: PACK },
  { text: 'The Amazing Spider-Man', lang: 'mix', pack: PACK },
  { text: 'Deadpool', lang: 'mix', pack: PACK },
  { text: 'Logan', lang: 'mix', pack: PACK },
  { text: 'X-Men', lang: 'mix', pack: PACK },
  { text: 'Frozen', lang: 'mix', pack: PACK },
  { text: 'Moana', lang: 'mix', pack: PACK },
  { text: 'Encanto', lang: 'mix', pack: PACK },
  { text: 'Coco', lang: 'mix', pack: PACK },
  { text: 'Inside Out', lang: 'mix', pack: PACK },
  { text: 'Toy Story', lang: 'mix', pack: PACK },
  { text: 'Finding Nemo', lang: 'mix', pack: PACK },
  { text: 'The Incredibles', lang: 'mix', pack: PACK },
  { text: 'Up', lang: 'mix', pack: PACK },
  { text: 'Wall-E', lang: 'mix', pack: PACK },
  { text: 'Shrek', lang: 'mix', pack: PACK },
  { text: 'Shrek 2', lang: 'mix', pack: PACK },
  { text: 'Kung Fu Panda', lang: 'mix', pack: PACK },
  { text: 'How to Train Your Dragon', lang: 'mix', pack: PACK },
  { text: 'The Lego Movie', lang: 'mix', pack: PACK },
  { text: 'The Lion King', lang: 'mix', pack: PACK },
  { text: 'Aladdin', lang: 'mix', pack: PACK },
  { text: 'Beauty and the Beast', lang: 'mix', pack: PACK },
  { text: 'The Little Mermaid', lang: 'mix', pack: PACK },
  { text: 'Mulan', lang: 'mix', pack: PACK },
  { text: 'Snow White', lang: 'mix', pack: PACK },
  { text: 'Cinderella', lang: 'mix', pack: PACK },
  { text: 'Sleeping Beauty', lang: 'mix', pack: PACK },
  { text: 'Peter Pan', lang: 'mix', pack: PACK },
  { text: 'Bambi', lang: 'mix', pack: PACK },
  { text: 'The Sound of Music', lang: 'mix', pack: PACK },
  { text: 'West Side Story', lang: 'mix', pack: PACK },
  { text: 'Grease', lang: 'mix', pack: PACK },
  { text: 'Mamma Mia', lang: 'mix', pack: PACK },
  { text: 'The Greatest Showman', lang: 'mix', pack: PACK },
  { text: 'Chicago', lang: 'mix', pack: PACK },
  { text: 'Les Misérables', lang: 'mix', pack: PACK },
  { text: 'Hamilton', lang: 'mix', pack: PACK },
  { text: 'Wicked', lang: 'mix', pack: PACK },
  { text: 'Mary Poppins', lang: 'mix', pack: PACK },
  { text: 'Pretty Woman', lang: 'mix', pack: PACK },
  { text: 'Notting Hill', lang: 'mix', pack: PACK },
  { text: 'Love Actually', lang: 'mix', pack: PACK },
  { text: 'The Notebook', lang: 'mix', pack: PACK },
  { text: 'Pride and Prejudice', lang: 'mix', pack: PACK },
  { text: 'Dirty Dancing', lang: 'mix', pack: PACK },
  { text: 'Ghost', lang: 'mix', pack: PACK },
  { text: 'Sleepless in Seattle', lang: 'mix', pack: PACK },
  { text: 'When Harry Met Sally', lang: 'mix', pack: PACK },
  { text: '10 Things I Hate About You', lang: 'mix', pack: PACK },
  { text: 'Mean Girls', lang: 'mix', pack: PACK },
  { text: 'Clueless', lang: 'mix', pack: PACK },
  { text: 'Legally Blonde', lang: 'mix', pack: PACK },
  { text: "Bridget Jones's Diary", lang: 'mix', pack: PACK },
  { text: 'The Devil Wears Prada', lang: 'mix', pack: PACK },
  { text: "Ocean's Eleven", lang: 'mix', pack: PACK },
  { text: 'The Italian Job', lang: 'mix', pack: PACK },
  { text: 'Catch Me If You Can', lang: 'mix', pack: PACK },
  { text: 'The Wolf of Wall Street', lang: 'mix', pack: PACK },
  { text: 'The Social Network', lang: 'mix', pack: PACK },
  { text: 'Fight Club', lang: 'mix', pack: PACK },
  { text: 'Se7en', lang: 'mix', pack: PACK },
  { text: 'Gone Girl', lang: 'mix', pack: PACK },
  { text: 'Zodiac', lang: 'mix', pack: PACK },
  { text: 'The Silence of the Lambs', lang: 'mix', pack: PACK },
  { text: 'The Exorcist', lang: 'mix', pack: PACK },
  { text: 'The Shining', lang: 'mix', pack: PACK },
  { text: 'Halloween', lang: 'mix', pack: PACK },
  { text: 'Scream', lang: 'mix', pack: PACK },
  { text: 'A Nightmare on Elm Street', lang: 'mix', pack: PACK },
  { text: 'Get Out', lang: 'mix', pack: PACK },
  { text: 'Hereditary', lang: 'mix', pack: PACK },
  { text: 'The Conjuring', lang: 'mix', pack: PACK },
  { text: 'It', lang: 'mix', pack: PACK },
  { text: 'The Ring', lang: 'mix', pack: PACK },
  { text: 'Mission: Impossible', lang: 'mix', pack: PACK },
  { text: 'James Bond', lang: 'mix', pack: PACK },
  { text: 'Casino Royale', lang: 'mix', pack: PACK },
  { text: 'Skyfall', lang: 'mix', pack: PACK },
  { text: 'No Time to Die', lang: 'mix', pack: PACK },
  { text: 'John Wick', lang: 'mix', pack: PACK },
  { text: 'Taken', lang: 'mix', pack: PACK },
  { text: 'The Bourne Identity', lang: 'mix', pack: PACK },
  { text: 'Jason Bourne', lang: 'mix', pack: PACK },
  { text: 'Kingsman', lang: 'mix', pack: PACK },
  { text: 'Pirates of the Caribbean', lang: 'mix', pack: PACK },
  { text: 'The Mummy', lang: 'mix', pack: PACK },
  { text: 'National Treasure', lang: 'mix', pack: PACK },
  { text: 'Night at the Museum', lang: 'mix', pack: PACK },
  { text: 'Jumanji', lang: 'mix', pack: PACK },
  { text: 'The Truman Show', lang: 'mix', pack: PACK },
  { text: 'The Grand Budapest Hotel', lang: 'mix', pack: PACK },
  { text: 'Amélie', lang: 'mix', pack: PACK },
  { text: 'Life is Beautiful', lang: 'mix', pack: PACK },
  { text: 'Cinema Paradiso', lang: 'mix', pack: PACK },
  { text: 'Spirited Away', lang: 'mix', pack: PACK },
  { text: 'My Neighbor Totoro', lang: 'mix', pack: PACK },
  { text: 'Princess Mononoke', lang: 'mix', pack: PACK },
  { text: 'Akira', lang: 'mix', pack: PACK },
  { text: 'Your Name', lang: 'mix', pack: PACK },
  { text: 'The Intouchables', lang: 'mix', pack: PACK },
  { text: 'Blue Is the Warmest Colour', lang: 'mix', pack: PACK },
  { text: 'Portrait of a Lady on Fire', lang: 'mix', pack: PACK },
  { text: 'Crouching Tiger Hidden Dragon', lang: 'mix', pack: PACK },
  { text: 'Soldaat van Oranje', lang: 'mix', pack: PACK },
  { text: 'Zwartboek', lang: 'mix', pack: PACK },
  { text: 'Turks Fruit', lang: 'mix', pack: PACK },
  { text: 'Karakter', lang: 'mix', pack: PACK },
  { text: 'De Aanslag', lang: 'mix', pack: PACK },
  { text: 'Alles is Liefde', lang: 'mix', pack: PACK },
  { text: 'Soof', lang: 'mix', pack: PACK },
  { text: 'Gooische Vrouwen', lang: 'mix', pack: PACK },
  { text: 'New Kids Turbo', lang: 'mix', pack: PACK },
  { text: 'Bon Voyage', lang: 'mix', pack: PACK },
  { text: 'Minoes', lang: 'mix', pack: PACK },
  { text: 'Kruistocht in spijkerbroek', lang: 'mix', pack: PACK },
  { text: 'Oorlogswinter', lang: 'mix', pack: PACK },
  { text: 'Bridget', lang: 'mix', pack: PACK },
  { text: 'Loenatik', lang: 'mix', pack: PACK },
  { text: 'Flodder', lang: 'mix', pack: PACK },
  { text: 'Schatjes', lang: 'mix', pack: PACK },
  { text: 'Ciske de Rat', lang: 'mix', pack: PACK },
  { text: 'Fanfare', lang: 'mix', pack: PACK },
  { text: 'Friends', lang: 'mix', pack: PACK },
  { text: 'The Office', lang: 'mix', pack: PACK },
  { text: 'Breaking Bad', lang: 'mix', pack: PACK },
  { text: 'Game of Thrones', lang: 'mix', pack: PACK },
  { text: 'Stranger Things', lang: 'mix', pack: PACK },
  { text: 'The Crown', lang: 'mix', pack: PACK },
  { text: 'The Witcher', lang: 'mix', pack: PACK },
  { text: 'Wednesday', lang: 'mix', pack: PACK },
  { text: 'Squid Game', lang: 'mix', pack: PACK },
  { text: 'Money Heist', lang: 'mix', pack: PACK },
  { text: 'Dark', lang: 'mix', pack: PACK },
  { text: 'The Bear', lang: 'mix', pack: PACK },
  { text: 'Succession', lang: 'mix', pack: PACK },
  { text: 'Ted Lasso', lang: 'mix', pack: PACK },
  { text: 'Only Murders in the Building', lang: 'mix', pack: PACK },
  { text: 'Seinfeld', lang: 'mix', pack: PACK },
  { text: 'Frasier', lang: 'mix', pack: PACK },
  { text: 'How I Met Your Mother', lang: 'mix', pack: PACK },
  { text: 'Brooklyn Nine-Nine', lang: 'mix', pack: PACK },
  { text: 'Parks and Recreation', lang: 'mix', pack: PACK },
  { text: 'The Simpsons', lang: 'mix', pack: PACK },
  { text: 'Family Guy', lang: 'mix', pack: PACK },
  { text: 'South Park', lang: 'mix', pack: PACK },
  { text: 'BoJack Horseman', lang: 'mix', pack: PACK },
  { text: 'Rick and Morty', lang: 'mix', pack: PACK },
  { text: 'Black Mirror', lang: 'mix', pack: PACK },
  { text: 'Westworld', lang: 'mix', pack: PACK },
  { text: 'Lost', lang: 'mix', pack: PACK },
  { text: 'Prison Break', lang: 'mix', pack: PACK },
  { text: '24', lang: 'mix', pack: PACK },
  { text: "Grey's Anatomy", lang: 'mix', pack: PACK },
  { text: 'ER', lang: 'mix', pack: PACK },
  { text: 'House', lang: 'mix', pack: PACK },
  { text: 'The Good Doctor', lang: 'mix', pack: PACK },
  { text: 'Scrubs', lang: 'mix', pack: PACK },
  { text: 'Law & Order', lang: 'mix', pack: PACK },
  { text: 'CSI', lang: 'mix', pack: PACK },
  { text: 'True Detective', lang: 'mix', pack: PACK },
  { text: 'Sherlock', lang: 'mix', pack: PACK },
  { text: 'Luther', lang: 'mix', pack: PACK },
  { text: 'Downton Abbey', lang: 'mix', pack: PACK },
  { text: 'Bridgerton', lang: 'mix', pack: PACK },
  { text: 'Outlander', lang: 'mix', pack: PACK },
  { text: "The Handmaid's Tale", lang: 'mix', pack: PACK },
  { text: 'Big Little Lies', lang: 'mix', pack: PACK },
  { text: 'Sex and the City', lang: 'mix', pack: PACK },
  { text: 'Girls', lang: 'mix', pack: PACK },
  { text: 'Euphoria', lang: 'mix', pack: PACK },
  { text: 'Skins', lang: 'mix', pack: PACK },
  { text: 'Gossip Girl', lang: 'mix', pack: PACK },
  { text: 'The Walking Dead', lang: 'mix', pack: PACK },
  { text: 'True Blood', lang: 'mix', pack: PACK },
  { text: 'Buffy the Vampire Slayer', lang: 'mix', pack: PACK },
  { text: 'Supernatural', lang: 'mix', pack: PACK },
  { text: 'Doctor Who', lang: 'mix', pack: PACK },
  { text: 'Star Trek', lang: 'mix', pack: PACK },
  { text: 'The Mandalorian', lang: 'mix', pack: PACK },
  { text: 'Andor', lang: 'mix', pack: PACK },
  { text: 'House of the Dragon', lang: 'mix', pack: PACK },
  { text: 'The Last of Us', lang: 'mix', pack: PACK },
  { text: 'Peaky Blinders', lang: 'mix', pack: PACK },
  { text: 'Narcos', lang: 'mix', pack: PACK },
  { text: 'Ozark', lang: 'mix', pack: PACK },
  { text: 'Better Call Saul', lang: 'mix', pack: PACK },
  { text: 'Fargo', lang: 'mix', pack: PACK },
  { text: 'The Big Bang Theory', lang: 'mix', pack: PACK },
  { text: 'Two and a Half Men', lang: 'mix', pack: PACK },
  { text: 'Modern Family', lang: 'mix', pack: PACK },
  { text: "Schitt's Creek", lang: 'mix', pack: PACK },
  { text: 'Community', lang: 'mix', pack: PACK },
  { text: 'Fawlty Towers', lang: 'mix', pack: PACK },
  { text: 'Monty Python', lang: 'mix', pack: PACK },
  { text: 'Blackadder', lang: 'mix', pack: PACK },
  { text: 'The IT Crowd', lang: 'mix', pack: PACK },
  { text: 'Baantjer', lang: 'mix', pack: PACK },
  { text: 'Flikken Maastricht', lang: 'mix', pack: PACK },
  { text: 'Penoza', lang: 'mix', pack: PACK },
  { text: 'Undercover', lang: 'mix', pack: PACK },
  { text: 'De Luizenmoeder', lang: 'mix', pack: PACK },
  { text: 'Wie is de Mol', lang: 'mix', pack: PACK },
  { text: 'Boer zoekt Vrouw', lang: 'mix', pack: PACK },
  { text: 'Expeditie Robinson', lang: 'mix', pack: PACK },
  { text: 'The Voice of Holland', lang: 'mix', pack: PACK },
  { text: "Holland's Next Top Model", lang: 'mix', pack: PACK },
  { text: 'Goede Tijden Slechte Tijden', lang: 'mix', pack: PACK },
  { text: 'Onderweg naar Morgen', lang: 'mix', pack: PACK },
  { text: 'Spangas', lang: 'mix', pack: PACK },
  { text: 'Het Huis Anubis', lang: 'mix', pack: PACK },
  { text: 'Koefnoen', lang: 'mix', pack: PACK },
  { text: 'Jiskefet', lang: 'mix', pack: PACK },
  { text: 'Van Kooten en De Bie', lang: 'mix', pack: PACK },
  { text: 'Koot & Bie', lang: 'mix', pack: PACK },
  { text: "Tata's", lang: 'mix', pack: PACK },
  { text: 'New Kids', lang: 'mix', pack: PACK },
  { text: 'Toen was geluk heel gewoon', lang: 'mix', pack: PACK },
  { text: 'Zaai', lang: 'mix', pack: PACK },
  { text: 'Kees & Co', lang: 'mix', pack: PACK },
  { text: 'Samson en Gert', lang: 'mix', pack: PACK },
  { text: 'Bassie en Adriaan', lang: 'mix', pack: PACK },
  { text: 'Sesamstraat', lang: 'mix', pack: PACK },
  { text: 'Teletubbies', lang: 'mix', pack: PACK },
  { text: 'PAW Patrol', lang: 'mix', pack: PACK },
  { text: 'Bluey', lang: 'mix', pack: PACK },
  { text: 'Peppa Pig', lang: 'mix', pack: PACK },
  { text: 'The Lion Guard', lang: 'mix', pack: PACK },
  { text: 'Dora the Explorer', lang: 'mix', pack: PACK },
  { text: 'SpongeBob SquarePants', lang: 'mix', pack: PACK },
  { text: 'The Fairly OddParents', lang: 'mix', pack: PACK },
  { text: 'Avatar: The Last Airbender', lang: 'mix', pack: PACK },
  { text: 'Arcane', lang: 'mix', pack: PACK },
  { text: 'The Boys', lang: 'mix', pack: PACK },
  { text: 'Fallout', lang: 'mix', pack: PACK },
  { text: 'The Penguin', lang: 'mix', pack: PACK },
  { text: 'Loki', lang: 'mix', pack: PACK },
  { text: 'WandaVision', lang: 'mix', pack: PACK },
  { text: 'Ms. Marvel', lang: 'mix', pack: PACK },
  { text: 'Moon Knight', lang: 'mix', pack: PACK },
  { text: 'Hawkeye', lang: 'mix', pack: PACK },
  { text: 'She-Hulk', lang: 'mix', pack: PACK },
  { text: 'Knives Out', lang: 'mix', pack: PACK },
  { text: 'Glass Onion', lang: 'mix', pack: PACK },
  { text: 'Murder on the Orient Express', lang: 'mix', pack: PACK },
  { text: 'Clue', lang: 'mix', pack: PACK },
  { text: 'The Menu', lang: 'mix', pack: PACK },
  { text: 'Cocoon', lang: 'mix', pack: PACK },
  { text: 'A Star Is Born', lang: 'mix', pack: PACK },
  { text: 'Bohemian Rhapsody', lang: 'mix', pack: PACK },
  { text: 'Elvis', lang: 'mix', pack: PACK },
  { text: 'Rocketman', lang: 'mix', pack: PACK },
  { text: 'Walk the Line', lang: 'mix', pack: PACK },
  { text: 'Ray', lang: 'mix', pack: PACK },
  { text: 'Straight Outta Compton', lang: 'mix', pack: PACK },
  { text: '8 Mile', lang: 'mix', pack: PACK },
];
