const PACK = 'music';
export const WORDS = [
  { text: 'The Beatles', lang: 'mix', pack: PACK },
  { text: 'The Rolling Stones', lang: 'mix', pack: PACK },
  { text: 'Led Zeppelin', lang: 'mix', pack: PACK },
  { text: 'Pink Floyd', lang: 'mix', pack: PACK },
  { text: 'Queen', lang: 'mix', pack: PACK },
  { text: 'AC/DC', lang: 'mix', pack: PACK },
  { text: 'Metallica', lang: 'mix', pack: PACK },
  { text: 'Nirvana', lang: 'mix', pack: PACK },
  { text: 'Pearl Jam', lang: 'mix', pack: PACK },
  { text: 'Red Hot Chili Peppers', lang: 'mix', pack: PACK },
  { text: 'U2', lang: 'mix', pack: PACK },
  { text: 'Coldplay', lang: 'mix', pack: PACK },
  { text: 'Radiohead', lang: 'mix', pack: PACK },
  { text: 'Oasis', lang: 'mix', pack: PACK },
  { text: 'Blur', lang: 'mix', pack: PACK },
  { text: 'ABBA', lang: 'mix', pack: PACK },
  { text: 'Bee Gees', lang: 'mix', pack: PACK },
  { text: 'The Beach Boys', lang: 'mix', pack: PACK },
  { text: 'The Who', lang: 'mix', pack: PACK },
  { text: 'The Doors', lang: 'mix', pack: PACK },
  { text: 'David Bowie', lang: 'mix', pack: PACK },
  { text: 'Elton John', lang: 'mix', pack: PACK },
  { text: 'Billy Joel', lang: 'mix', pack: PACK },
  { text: 'Bruce Springsteen', lang: 'mix', pack: PACK },
  { text: 'Bob Dylan', lang: 'mix', pack: PACK },
  { text: 'Johnny Cash', lang: 'mix', pack: PACK },
  { text: 'Willie Nelson', lang: 'mix', pack: PACK },
  { text: 'Dolly Parton', lang: 'mix', pack: PACK },
  { text: 'Taylor Swift', lang: 'mix', pack: PACK },
  { text: 'Carrie Underwood', lang: 'mix', pack: PACK },
  { text: 'Madonna', lang: 'mix', pack: PACK },
  { text: 'Michael Jackson', lang: 'mix', pack: PACK },
  { text: 'Prince', lang: 'mix', pack: PACK },
  { text: 'Whitney Houston', lang: 'mix', pack: PACK },
  { text: 'Mariah Carey', lang: 'mix', pack: PACK },
  { text: 'Celine Dion', lang: 'mix', pack: PACK },
  { text: 'Adele', lang: 'mix', pack: PACK },
  { text: 'Amy Winehouse', lang: 'mix', pack: PACK },
  { text: 'Duffy', lang: 'mix', pack: PACK },
  { text: 'Sia', lang: 'mix', pack: PACK },
  { text: 'Beyoncé', lang: 'mix', pack: PACK },
  { text: 'Rihanna', lang: 'mix', pack: PACK },
  { text: 'Lady Gaga', lang: 'mix', pack: PACK },
  { text: 'Katy Perry', lang: 'mix', pack: PACK },
  { text: 'Britney Spears', lang: 'mix', pack: PACK },
  { text: 'Christina Aguilera', lang: 'mix', pack: PACK },
  { text: 'Jennifer Lopez', lang: 'mix', pack: PACK },
  { text: 'Shakira', lang: 'mix', pack: PACK },
  { text: 'Nelly Furtado', lang: 'mix', pack: PACK },
  { text: 'Dua Lipa', lang: 'mix', pack: PACK },
  { text: 'Billie Eilish', lang: 'mix', pack: PACK },
  { text: 'Olivia Rodrigo', lang: 'mix', pack: PACK },
  { text: 'Ariana Grande', lang: 'mix', pack: PACK },
  { text: 'Miley Cyrus', lang: 'mix', pack: PACK },
  { text: 'Selena Gomez', lang: 'mix', pack: PACK },
  { text: 'Harry Styles', lang: 'mix', pack: PACK },
  { text: 'Ed Sheeran', lang: 'mix', pack: PACK },
  { text: 'Sam Smith', lang: 'mix', pack: PACK },
  { text: 'Shawn Mendes', lang: 'mix', pack: PACK },
  { text: 'Justin Bieber', lang: 'mix', pack: PACK },
  { text: 'The Weeknd', lang: 'mix', pack: PACK },
  { text: 'Drake', lang: 'mix', pack: PACK },
  { text: 'Kanye West', lang: 'mix', pack: PACK },
  { text: 'Jay-Z', lang: 'mix', pack: PACK },
  { text: 'Eminem', lang: 'mix', pack: PACK },
  { text: 'Snoop Dogg', lang: 'mix', pack: PACK },
  { text: 'Dr. Dre', lang: 'mix', pack: PACK },
  { text: 'Tupac', lang: 'mix', pack: PACK },
  { text: 'The Notorious B.I.G.', lang: 'mix', pack: PACK },
  { text: 'Kendrick Lamar', lang: 'mix', pack: PACK },
  { text: 'Travis Scott', lang: 'mix', pack: PACK },
  { text: 'Post Malone', lang: 'mix', pack: PACK },
  { text: 'Lil Nas X', lang: 'mix', pack: PACK },
  { text: 'Doja Cat', lang: 'mix', pack: PACK },
  { text: 'Nicki Minaj', lang: 'mix', pack: PACK },
  { text: 'Bob Marley', lang: 'mix', pack: PACK },
  { text: 'Jimmy Cliff', lang: 'mix', pack: PACK },
  { text: 'UB40', lang: 'mix', pack: PACK },
  { text: 'Sean Paul', lang: 'mix', pack: PACK },
  { text: 'Shaggy', lang: 'mix', pack: PACK },
  { text: 'Stevie Wonder', lang: 'mix', pack: PACK },
  { text: 'Aretha Franklin', lang: 'mix', pack: PACK },
  { text: 'Tina Turner', lang: 'mix', pack: PACK },
  { text: 'James Brown', lang: 'mix', pack: PACK },
  { text: 'Marvin Gaye', lang: 'mix', pack: PACK },
  { text: 'Diana Ross', lang: 'mix', pack: PACK },
  { text: 'The Supremes', lang: 'mix', pack: PACK },
  { text: 'The Temptations', lang: 'mix', pack: PACK },
  { text: 'Earth Wind & Fire', lang: 'mix', pack: PACK },
  { text: 'Chic', lang: 'mix', pack: PACK },
  { text: 'Daft Punk', lang: 'mix', pack: PACK },
  { text: 'The Chemical Brothers', lang: 'mix', pack: PACK },
  { text: 'Fatboy Slim', lang: 'mix', pack: PACK },
  { text: 'Calvin Harris', lang: 'mix', pack: PACK },
  { text: 'David Guetta', lang: 'mix', pack: PACK },
  { text: 'Avicii', lang: 'mix', pack: PACK },
  { text: 'Swedish House Mafia', lang: 'mix', pack: PACK },
  { text: 'Kygo', lang: 'mix', pack: PACK },
  { text: 'Marshmello', lang: 'mix', pack: PACK },
  { text: 'Deadmau5', lang: 'mix', pack: PACK },
  { text: 'Tiësto', lang: 'mix', pack: PACK },
  { text: 'Armin van Buuren', lang: 'mix', pack: PACK },
  { text: 'Martin Garrix', lang: 'mix', pack: PACK },
  { text: 'Hardwell', lang: 'mix', pack: PACK },
  { text: 'Oliver Heldens', lang: 'mix', pack: PACK },
  { text: 'André Hazes', lang: 'mix', pack: PACK },
  { text: 'Frans Bauer', lang: 'mix', pack: PACK },
  { text: 'Jan Smit', lang: 'mix', pack: PACK },
  { text: 'Guus Meeuwis', lang: 'mix', pack: PACK },
  { text: 'Marco Borsato', lang: 'mix', pack: PACK },
  { text: 'Acda en De Munnik', lang: 'mix', pack: PACK },
  { text: 'BLØF', lang: 'mix', pack: PACK },
  { text: 'Doe Maar', lang: 'mix', pack: PACK },
  { text: 'Golden Earring', lang: 'mix', pack: PACK },
  { text: 'The Scene', lang: 'mix', pack: PACK },
  { text: 'Anouk', lang: 'mix', pack: PACK },
  { text: 'Ilse DeLange', lang: 'mix', pack: PACK },
  { text: 'Trijntje Oosterhuis', lang: 'mix', pack: PACK },
  { text: 'Within Temptation', lang: 'mix', pack: PACK },
  { text: 'Epica', lang: 'mix', pack: PACK },
  { text: 'Kensington', lang: 'mix', pack: PACK },
  { text: "Chef'Special", lang: 'mix', pack: PACK },
  { text: 'De Jeugd van Tegenwoordig', lang: 'mix', pack: PACK },
  { text: 'Kraantje Pappie', lang: 'mix', pack: PACK },
  { text: 'Ronnie Flex', lang: 'mix', pack: PACK },
  { text: "Lil' Kleine", lang: 'mix', pack: PACK },
  { text: 'Broederliefde', lang: 'mix', pack: PACK },
  { text: 'Snelle', lang: 'mix', pack: PACK },
  { text: 'Maan', lang: 'mix', pack: PACK },
  { text: 'Davina Michelle', lang: 'mix', pack: PACK },
  { text: 'Duncan Laurence', lang: 'mix', pack: PACK },
  { text: 'S10', lang: 'mix', pack: PACK },
  { text: 'Claude', lang: 'mix', pack: PACK },
  { text: 'Joost', lang: 'mix', pack: PACK },
  { text: 'Goldband', lang: 'mix', pack: PACK },
  { text: 'Froukje', lang: 'mix', pack: PACK },
  { text: 'Eefje de Visser', lang: 'mix', pack: PACK },
  { text: 'Spinvis', lang: 'mix', pack: PACK },
  { text: 'Van Dik Hout', lang: 'mix', pack: PACK },
  { text: 'Rowwen Hèze', lang: 'mix', pack: PACK },
  { text: 'Normaal', lang: 'mix', pack: PACK },
  { text: 'Heideroosjes', lang: 'mix', pack: PACK },
  { text: 'Di-rect', lang: 'mix', pack: PACK },
  { text: 'Kane', lang: 'mix', pack: PACK },
  { text: 'VanVelzen', lang: 'mix', pack: PACK },
  { text: 'Racoon', lang: 'mix', pack: PACK },
  { text: 'Nielson', lang: 'mix', pack: PACK },
  { text: 'Miss Montreal', lang: 'mix', pack: PACK },
  { text: 'Douwe Bob', lang: 'mix', pack: PACK },
  { text: 'Waylon', lang: 'mix', pack: PACK },
  { text: 'The Common Linnets', lang: 'mix', pack: PACK },
  { text: 'Nick & Simon', lang: 'mix', pack: PACK },
  { text: '3JS', lang: 'mix', pack: PACK },
  { text: 'Volumia!', lang: 'mix', pack: PACK },
  { text: 'Krezip', lang: 'mix', pack: PACK },
  { text: 'Bohemian Rhapsody', lang: 'mix', pack: PACK },
  { text: "Don't Stop Me Now", lang: 'mix', pack: PACK },
  { text: 'We Will Rock You', lang: 'mix', pack: PACK },
  { text: 'We Are the Champions', lang: 'mix', pack: PACK },
  { text: 'Somebody to Love', lang: 'mix', pack: PACK },
  { text: 'Stairway to Heaven', lang: 'mix', pack: PACK },
  { text: 'Hotel California', lang: 'mix', pack: PACK },
  { text: "Sweet Child o' Mine", lang: 'mix', pack: PACK },
  { text: 'Smells Like Teen Spirit', lang: 'mix', pack: PACK },
  { text: 'Wonderwall', lang: 'mix', pack: PACK },
  { text: 'Hey Jude', lang: 'mix', pack: PACK },
  { text: 'Let It Be', lang: 'mix', pack: PACK },
  { text: 'Yesterday', lang: 'mix', pack: PACK },
  { text: 'Come Together', lang: 'mix', pack: PACK },
  { text: 'Help!', lang: 'mix', pack: PACK },
  { text: 'Billie Jean', lang: 'mix', pack: PACK },
  { text: 'Thriller', lang: 'mix', pack: PACK },
  { text: 'Beat It', lang: 'mix', pack: PACK },
  { text: 'Smooth Criminal', lang: 'mix', pack: PACK },
  { text: 'Bad', lang: 'mix', pack: PACK },
  { text: 'Like a Prayer', lang: 'mix', pack: PACK },
  { text: 'Vogue', lang: 'mix', pack: PACK },
  { text: 'Material Girl', lang: 'mix', pack: PACK },
  { text: 'Hung Up', lang: 'mix', pack: PACK },
  { text: 'Music', lang: 'mix', pack: PACK },
  { text: 'Rolling in the Deep', lang: 'mix', pack: PACK },
  { text: 'Someone Like You', lang: 'mix', pack: PACK },
  { text: 'Hello', lang: 'mix', pack: PACK },
  { text: 'Skyfall', lang: 'mix', pack: PACK },
  { text: 'Set Fire to the Rain', lang: 'mix', pack: PACK },
  { text: 'Shape of You', lang: 'mix', pack: PACK },
  { text: 'Perfect', lang: 'mix', pack: PACK },
  { text: 'Thinking Out Loud', lang: 'mix', pack: PACK },
  { text: 'Bad Habits', lang: 'mix', pack: PACK },
  { text: 'Photograph', lang: 'mix', pack: PACK },
  { text: 'Blinding Lights', lang: 'mix', pack: PACK },
  { text: 'Starboy', lang: 'mix', pack: PACK },
  { text: 'Save Your Tears', lang: 'mix', pack: PACK },
  { text: 'The Hills', lang: 'mix', pack: PACK },
  { text: "Can't Feel My Face", lang: 'mix', pack: PACK },
  { text: 'Old Town Road', lang: 'mix', pack: PACK },
  { text: 'Drivers License', lang: 'mix', pack: PACK },
  { text: 'Good 4 U', lang: 'mix', pack: PACK },
  { text: 'Anti-Hero', lang: 'mix', pack: PACK },
  { text: 'Shake It Off', lang: 'mix', pack: PACK },
  { text: 'Blank Space', lang: 'mix', pack: PACK },
  { text: 'Love Story', lang: 'mix', pack: PACK },
  { text: 'You Belong with Me', lang: 'mix', pack: PACK },
  { text: 'All Too Well', lang: 'mix', pack: PACK },
  { text: 'Cruel Summer', lang: 'mix', pack: PACK },
  { text: 'Umbrella', lang: 'mix', pack: PACK },
  { text: 'Diamonds', lang: 'mix', pack: PACK },
  { text: 'Stay', lang: 'mix', pack: PACK },
  { text: 'We Found Love', lang: 'mix', pack: PACK },
  { text: 'Only Girl', lang: 'mix', pack: PACK },
  { text: 'Poker Face', lang: 'mix', pack: PACK },
  { text: 'Bad Romance', lang: 'mix', pack: PACK },
  { text: 'Shallow', lang: 'mix', pack: PACK },
  { text: 'Born This Way', lang: 'mix', pack: PACK },
  { text: 'Just Dance', lang: 'mix', pack: PACK },
  { text: 'Single Ladies', lang: 'mix', pack: PACK },
  { text: 'Halo', lang: 'mix', pack: PACK },
  { text: 'Crazy in Love', lang: 'mix', pack: PACK },
  { text: 'Formation', lang: 'mix', pack: PACK },
  { text: "Texas Hold 'Em", lang: 'mix', pack: PACK },
  { text: 'Despacito', lang: 'mix', pack: PACK },
  { text: 'Macarena', lang: 'mix', pack: PACK },
  { text: 'Gangnam Style', lang: 'mix', pack: PACK },
  { text: 'Baby Shark', lang: 'mix', pack: PACK },
  { text: 'Happy', lang: 'mix', pack: PACK },
  { text: 'Uptown Funk', lang: 'mix', pack: PACK },
  { text: 'Get Lucky', lang: 'mix', pack: PACK },
  { text: 'Wake Me Up', lang: 'mix', pack: PACK },
  { text: 'Levels', lang: 'mix', pack: PACK },
  { text: 'Titanium', lang: 'mix', pack: PACK },
  { text: 'I Gotta Feeling', lang: 'mix', pack: PACK },
  { text: 'Mr. Brightside', lang: 'mix', pack: PACK },
  { text: 'Take On Me', lang: 'mix', pack: PACK },
  { text: 'Africa', lang: 'mix', pack: PACK },
  { text: "Don't Stop Believin'", lang: 'mix', pack: PACK },
  { text: 'Sweet Caroline', lang: 'mix', pack: PACK },
  { text: "Livin' on a Prayer", lang: 'mix', pack: PACK },
  { text: 'Eye of the Tiger', lang: 'mix', pack: PACK },
  { text: "We Didn't Start the Fire", lang: 'mix', pack: PACK },
  { text: 'Piano Man', lang: 'mix', pack: PACK },
  { text: 'Imagine', lang: 'mix', pack: PACK },
  { text: 'What a Wonderful World', lang: 'mix', pack: PACK },
  { text: 'My Way', lang: 'mix', pack: PACK },
  { text: 'New York New York', lang: 'mix', pack: PACK },
  { text: 'Fly Me to the Moon', lang: 'mix', pack: PACK },
  { text: 'La Bamba', lang: 'mix', pack: PACK },
  { text: 'Guantanamera', lang: 'mix', pack: PACK },
  { text: 'Bésame Mucho', lang: 'mix', pack: PACK },
  { text: 'La Vie en Rose', lang: 'mix', pack: PACK },
  { text: 'Non, je ne regrette rien', lang: 'mix', pack: PACK },
  { text: 'jazz', lang: 'mix', pack: PACK },
  { text: 'blues', lang: 'mix', pack: PACK },
  { text: 'rock', lang: 'mix', pack: PACK },
  { text: 'pop', lang: 'mix', pack: PACK },
  { text: 'hip hop', lang: 'mix', pack: PACK },
  { text: 'reggae', lang: 'mix', pack: PACK },
  { text: 'country', lang: 'mix', pack: PACK },
  { text: 'folk', lang: 'mix', pack: PACK },
  { text: 'classical', lang: 'mix', pack: PACK },
  { text: 'opera', lang: 'mix', pack: PACK },
  { text: 'disco', lang: 'mix', pack: PACK },
  { text: 'funk', lang: 'mix', pack: PACK },
  { text: 'soul', lang: 'mix', pack: PACK },
  { text: 'R&B', lang: 'mix', pack: PACK },
  { text: 'techno', lang: 'mix', pack: PACK },
  { text: 'house', lang: 'mix', pack: PACK },
  { text: 'trance', lang: 'mix', pack: PACK },
  { text: 'drum and bass', lang: 'mix', pack: PACK },
  { text: 'gabber', lang: 'mix', pack: PACK },
  { text: 'hardstyle', lang: 'mix', pack: PACK },
  { text: 'metal', lang: 'mix', pack: PACK },
  { text: 'punk', lang: 'mix', pack: PACK },
  { text: 'indie', lang: 'mix', pack: PACK },
  { text: 'k-pop', lang: 'mix', pack: PACK },
  { text: 'latin', lang: 'mix', pack: PACK },
  { text: 'guitar', lang: 'mix', pack: PACK },
  { text: 'piano', lang: 'mix', pack: PACK },
  { text: 'drums', lang: 'mix', pack: PACK },
  { text: 'violin', lang: 'mix', pack: PACK },
  { text: 'saxophone', lang: 'mix', pack: PACK },
  { text: 'trumpet', lang: 'mix', pack: PACK },
  { text: 'harmonica', lang: 'mix', pack: PACK },
  { text: 'ukulele', lang: 'mix', pack: PACK },
  { text: 'bass guitar', lang: 'mix', pack: PACK },
  { text: 'synthesizer', lang: 'mix', pack: PACK },
  { text: 'microphone', lang: 'mix', pack: PACK },
  { text: 'karaoke', lang: 'mix', pack: PACK },
  { text: 'festival', lang: 'mix', pack: PACK },
  { text: 'concert', lang: 'mix', pack: PACK },
  { text: 'album', lang: 'mix', pack: PACK },
  { text: 'single', lang: 'mix', pack: PACK },
  { text: 'remix', lang: 'mix', pack: PACK },
  { text: 'cover', lang: 'mix', pack: PACK },
  { text: 'duet', lang: 'mix', pack: PACK },
  { text: 'choir', lang: 'mix', pack: PACK },
  { text: 'Eurovision', lang: 'mix', pack: PACK },
  { text: 'Grammy', lang: 'mix', pack: PACK },
  { text: 'MTV', lang: 'mix', pack: PACK },
  { text: 'Top 40', lang: 'mix', pack: PACK },
  { text: 'Spotify Wrapped', lang: 'mix', pack: PACK },
  { text: 'Woodstock', lang: 'mix', pack: PACK },
  { text: 'Glastonbury', lang: 'mix', pack: PACK },
  { text: 'Coachella', lang: 'mix', pack: PACK },
  { text: 'Pinkpop', lang: 'mix', pack: PACK },
  { text: 'Lowlands', lang: 'mix', pack: PACK },
  { text: 'Tomorrowland', lang: 'mix', pack: PACK },
  { text: 'Mysteryland', lang: 'mix', pack: PACK },
  { text: 'Awakenings', lang: 'mix', pack: PACK },
  { text: 'Defqon.1', lang: 'mix', pack: PACK },
  { text: 'Dance Valley', lang: 'mix', pack: PACK },
  { text: 'Het Concertgebouw', lang: 'mix', pack: PACK },
  { text: 'Paradiso', lang: 'mix', pack: PACK },
  { text: 'Melkweg', lang: 'mix', pack: PACK },
  { text: 'Ahoy', lang: 'mix', pack: PACK },
  { text: 'Ziggo Dome', lang: 'mix', pack: PACK },
  { text: 'Johan Cruijff Arena', lang: 'mix', pack: PACK },
  { text: 'GelreDome', lang: 'mix', pack: PACK },
  { text: 'De Kuip', lang: 'mix', pack: PACK },
  { text: 'AFAS Live', lang: 'mix', pack: PACK },
  { text: '013 Tilburg', lang: 'mix', pack: PACK },
  { text: 'Breng me naar het water', lang: 'mix', pack: PACK },
  { text: 'Het is een nacht', lang: 'mix', pack: PACK },
  { text: 'Zij gelooft in mij', lang: 'mix', pack: PACK },
  { text: 'Mag ik dan bij jou', lang: 'mix', pack: PACK },
  { text: 'Blijf bij mij', lang: 'mix', pack: PACK },
  { text: '15 miljoen mensen', lang: 'mix', pack: PACK },
  { text: 'Radar Love', lang: 'mix', pack: PACK },
  { text: 'When the Lady Smiles', lang: 'mix', pack: PACK },
  { text: 'Twilight Zone', lang: 'mix', pack: PACK },
  { text: 'Iedereen is van de wereld', lang: 'mix', pack: PACK },
  { text: 'Kronenburg Park', lang: 'mix', pack: PACK },
  { text: 'Zij maakt het verschil', lang: 'mix', pack: PACK },
  { text: 'Onderweg', lang: 'mix', pack: PACK },
  { text: 'Harder dan ik hebben kan', lang: 'mix', pack: PACK },
  { text: "They Don't Know", lang: 'mix', pack: PACK },
  { text: 'Nobody Else', lang: 'mix', pack: PACK },
  { text: 'Animals', lang: 'mix', pack: PACK },
  { text: 'Pizza', lang: 'mix', pack: PACK },
  { text: 'In the Name of Love', lang: 'mix', pack: PACK },
  { text: 'This Is What It Feels Like', lang: 'mix', pack: PACK },
  { text: 'Adagio for Strings', lang: 'mix', pack: PACK },
  { text: 'Silence', lang: 'mix', pack: PACK },
  { text: 'Gouryella', lang: 'mix', pack: PACK },
  { text: 'Traffic', lang: 'mix', pack: PACK },
];
