const PACK = 'nl_general';
export const WORDS = [
  { text: 'Max Verstappen', lang: 'nl', pack: PACK },
  { text: 'Johan Cruijff', lang: 'nl', pack: PACK },
  { text: 'André Hazes', lang: 'nl', pack: PACK },
  { text: 'André van Duin', lang: 'nl', pack: PACK },
  { text: 'Chantal Janzen', lang: 'nl', pack: PACK },
  { text: 'Linda de Mol', lang: 'nl', pack: PACK },
  { text: 'Gordon', lang: 'nl', pack: PACK },
  { text: 'Guus Meeuwis', lang: 'nl', pack: PACK },
  { text: 'Anouk', lang: 'nl', pack: PACK },
  { text: 'Armin van Buuren', lang: 'nl', pack: PACK },
  { text: 'Tiësto', lang: 'nl', pack: PACK },
  { text: 'Martin Garrix', lang: 'nl', pack: PACK },
  { text: 'Duncan Laurence', lang: 'nl', pack: PACK },
  { text: 'Eva Jinek', lang: 'nl', pack: PACK },
  { text: 'Matthijs van Nieuwkerk', lang: 'nl', pack: PACK },
  { text: 'Beau van Erven Dorens', lang: 'nl', pack: PACK },
  { text: 'Humberto Tan', lang: 'nl', pack: PACK },
  { text: 'Sylvana Simons', lang: 'nl', pack: PACK },
  { text: 'Thierry Baudet', lang: 'nl', pack: PACK },
  { text: 'Mark Rutte', lang: 'nl', pack: PACK },
  { text: 'Willem-Alexander', lang: 'nl', pack: PACK },
  { text: 'Máxima', lang: 'nl', pack: PACK },
  { text: 'Prinses Amalia', lang: 'nl', pack: PACK },
  { text: 'Prins Bernhard', lang: 'nl', pack: PACK },
  { text: 'Anne Frank', lang: 'nl', pack: PACK },
  { text: 'Vincent van Gogh', lang: 'nl', pack: PACK },
  { text: 'Rembrandt', lang: 'nl', pack: PACK },
  { text: 'Erasmus', lang: 'nl', pack: PACK },
  { text: 'Spinoza', lang: 'nl', pack: PACK },
  { text: 'Piet Mondriaan', lang: 'nl', pack: PACK },
  { text: 'M.C. Escher', lang: 'nl', pack: PACK },
  { text: 'Dick Bruna', lang: 'nl', pack: PACK },
  { text: 'Wim T. Schippers', lang: 'nl', pack: PACK },
  { text: 'Paul de Leeuw', lang: 'nl', pack: PACK },
  { text: "Youp van 't Hek", lang: 'nl', pack: PACK },
  { text: 'Freek de Jonge', lang: 'nl', pack: PACK },
  { text: 'Theo Maassen', lang: 'nl', pack: PACK },
  { text: 'Jochem Myjer', lang: 'nl', pack: PACK },
  { text: 'Claudia de Breij', lang: 'nl', pack: PACK },
  { text: 'Najib Amhali', lang: 'nl', pack: PACK },
  { text: 'Ali B', lang: 'nl', pack: PACK },
  { text: 'Yes-R', lang: 'nl', pack: PACK },
  { text: 'Broederliefde', lang: 'nl', pack: PACK },
  { text: 'Snelle', lang: 'nl', pack: PACK },
  { text: 'Maan', lang: 'nl', pack: PACK },
  { text: 'Davina Michelle', lang: 'nl', pack: PACK },
  { text: 'Ilse DeLange', lang: 'nl', pack: PACK },
  { text: 'Trijntje Oosterhuis', lang: 'nl', pack: PACK },
  { text: 'Marco Borsato', lang: 'nl', pack: PACK },
  { text: 'Jan Smit', lang: 'nl', pack: PACK },
  { text: 'Frans Bauer', lang: 'nl', pack: PACK },
  { text: 'Nick & Simon', lang: 'nl', pack: PACK },
  { text: 'Acda en De Munnik', lang: 'nl', pack: PACK },
  { text: 'BLØF', lang: 'nl', pack: PACK },
  { text: 'Doe Maar', lang: 'nl', pack: PACK },
  { text: 'Golden Earring', lang: 'nl', pack: PACK },
  { text: 'Within Temptation', lang: 'nl', pack: PACK },
  { text: 'Epica', lang: 'nl', pack: PACK },
  { text: 'Focus', lang: 'nl', pack: PACK },
  { text: 'Amsterdam', lang: 'nl', pack: PACK },
  { text: 'Rotterdam', lang: 'nl', pack: PACK },
  { text: 'Utrecht', lang: 'nl', pack: PACK },
  { text: 'Den Haag', lang: 'nl', pack: PACK },
  { text: 'Eindhoven', lang: 'nl', pack: PACK },
  { text: 'Groningen', lang: 'nl', pack: PACK },
  { text: 'Maastricht', lang: 'nl', pack: PACK },
  { text: 'Haarlem', lang: 'nl', pack: PACK },
  { text: 'Leiden', lang: 'nl', pack: PACK },
  { text: 'Delft', lang: 'nl', pack: PACK },
  { text: 'Nijmegen', lang: 'nl', pack: PACK },
  { text: 'Arnhem', lang: 'nl', pack: PACK },
  { text: 'Tilburg', lang: 'nl', pack: PACK },
  { text: 'Breda', lang: 'nl', pack: PACK },
  { text: 'Zwolle', lang: 'nl', pack: PACK },
  { text: 'Almere', lang: 'nl', pack: PACK },
  { text: 'Amersfoort', lang: 'nl', pack: PACK },
  { text: 'Apeldoorn', lang: 'nl', pack: PACK },
  { text: 'Enschede', lang: 'nl', pack: PACK },
  { text: 'Leeuwarden', lang: 'nl', pack: PACK },
  { text: 'Middelburg', lang: 'nl', pack: PACK },
  { text: 'Vlissingen', lang: 'nl', pack: PACK },
  { text: 'Scheveningen', lang: 'nl', pack: PACK },
  { text: 'Zandvoort', lang: 'nl', pack: PACK },
  { text: 'Volendam', lang: 'nl', pack: PACK },
  { text: 'Marken', lang: 'nl', pack: PACK },
  { text: 'Giethoorn', lang: 'nl', pack: PACK },
  { text: 'Kinderdijk', lang: 'nl', pack: PACK },
  { text: 'Keukenhof', lang: 'nl', pack: PACK },
  { text: 'Efteling', lang: 'nl', pack: PACK },
  { text: 'Madurodam', lang: 'nl', pack: PACK },
  { text: 'Artis', lang: 'nl', pack: PACK },
  { text: 'NEMO', lang: 'nl', pack: PACK },
  { text: 'Rijksmuseum', lang: 'nl', pack: PACK },
  { text: 'Van Gogh Museum', lang: 'nl', pack: PACK },
  { text: 'Anne Frank Huis', lang: 'nl', pack: PACK },
  { text: 'Euromast', lang: 'nl', pack: PACK },
  { text: 'Erasmusbrug', lang: 'nl', pack: PACK },
  { text: 'Domtoren', lang: 'nl', pack: PACK },
  { text: 'Martinitoren', lang: 'nl', pack: PACK },
  { text: 'Afsluitdijk', lang: 'nl', pack: PACK },
  { text: 'Deltawerken', lang: 'nl', pack: PACK },
  { text: 'Waddeneilanden', lang: 'nl', pack: PACK },
  { text: 'Texel', lang: 'nl', pack: PACK },
  { text: 'Terschelling', lang: 'nl', pack: PACK },
  { text: 'Schiphol', lang: 'nl', pack: PACK },
  { text: 'NS', lang: 'nl', pack: PACK },
  { text: 'OV-chipkaart', lang: 'nl', pack: PACK },
  { text: 'fiets', lang: 'nl', pack: PACK },
  { text: 'brommer', lang: 'nl', pack: PACK },
  { text: 'gracht', lang: 'nl', pack: PACK },
  { text: 'molen', lang: 'nl', pack: PACK },
  { text: 'klompen', lang: 'nl', pack: PACK },
  { text: 'tulpen', lang: 'nl', pack: PACK },
  { text: 'kaas', lang: 'nl', pack: PACK },
  { text: 'haring', lang: 'nl', pack: PACK },
  { text: 'stroopwafel', lang: 'nl', pack: PACK },
  { text: 'drop', lang: 'nl', pack: PACK },
  { text: 'hagelslag', lang: 'nl', pack: PACK },
  { text: 'pindakaas', lang: 'nl', pack: PACK },
  { text: 'kroket', lang: 'nl', pack: PACK },
  { text: 'bitterballen', lang: 'nl', pack: PACK },
  { text: 'poffertjes', lang: 'nl', pack: PACK },
  { text: 'pannenkoeken', lang: 'nl', pack: PACK },
  { text: 'erwtensoep', lang: 'nl', pack: PACK },
  { text: 'stamppot', lang: 'nl', pack: PACK },
  { text: 'boerenkool', lang: 'nl', pack: PACK },
  { text: 'hutspot', lang: 'nl', pack: PACK },
  { text: 'kapucijners', lang: 'nl', pack: PACK },
  { text: 'oliebol', lang: 'nl', pack: PACK },
  { text: 'appeltaart', lang: 'nl', pack: PACK },
  { text: 'vla', lang: 'nl', pack: PACK },
  { text: 'chocoladeletter', lang: 'nl', pack: PACK },
  { text: 'pepernoten', lang: 'nl', pack: PACK },
  { text: 'speculaas', lang: 'nl', pack: PACK },
  { text: 'tompouce', lang: 'nl', pack: PACK },
  { text: 'bossche bol', lang: 'nl', pack: PACK },
  { text: 'ontbijtkoek', lang: 'nl', pack: PACK },
  { text: 'beschuit', lang: 'nl', pack: PACK },
  { text: 'pindasaus', lang: 'nl', pack: PACK },
  { text: 'friet', lang: 'nl', pack: PACK },
  { text: 'mayo', lang: 'nl', pack: PACK },
  { text: 'saté', lang: 'nl', pack: PACK },
  { text: 'rijsttafel', lang: 'nl', pack: PACK },
  { text: 'nasi', lang: 'nl', pack: PACK },
  { text: 'bami', lang: 'nl', pack: PACK },
  { text: 'loempia', lang: 'nl', pack: PACK },
  { text: 'kibbeling', lang: 'nl', pack: PACK },
  { text: 'lekkerbek', lang: 'nl', pack: PACK },
  { text: 'patatje oorlog', lang: 'nl', pack: PACK },
  { text: 'HEMA', lang: 'nl', pack: PACK },
  { text: 'Albert Heijn', lang: 'nl', pack: PACK },
  { text: 'Jumbo', lang: 'nl', pack: PACK },
  { text: 'Kruidvat', lang: 'nl', pack: PACK },
  { text: 'Action', lang: 'nl', pack: PACK },
  { text: 'Blokker', lang: 'nl', pack: PACK },
  { text: 'Ikea', lang: 'nl', pack: PACK },
  { text: 'MediaMarkt', lang: 'nl', pack: PACK },
  { text: 'Coolblue', lang: 'nl', pack: PACK },
  { text: 'Bol.com', lang: 'nl', pack: PACK },
  { text: 'KPN', lang: 'nl', pack: PACK },
  { text: 'Vodafone', lang: 'nl', pack: PACK },
  { text: 'ING', lang: 'nl', pack: PACK },
  { text: 'Rabobank', lang: 'nl', pack: PACK },
  { text: 'ABN AMRO', lang: 'nl', pack: PACK },
  { text: 'KLM', lang: 'nl', pack: PACK },
  { text: 'TUI', lang: 'nl', pack: PACK },
  { text: 'ANWB', lang: 'nl', pack: PACK },
  { text: 'PostNL', lang: 'nl', pack: PACK },
  { text: 'Belastingdienst', lang: 'nl', pack: PACK },
  { text: 'Rijkswaterstaat', lang: 'nl', pack: PACK },
  { text: 'politie', lang: 'nl', pack: PACK },
  { text: 'brandweer', lang: 'nl', pack: PACK },
  { text: 'ambulance', lang: 'nl', pack: PACK },
  { text: 'huisarts', lang: 'nl', pack: PACK },
  { text: 'tandarts', lang: 'nl', pack: PACK },
  { text: 'apotheek', lang: 'nl', pack: PACK },
  { text: 'supermarkt', lang: 'nl', pack: PACK },
  { text: 'markt', lang: 'nl', pack: PACK },
  { text: 'braderie', lang: 'nl', pack: PACK },
  { text: 'kermis', lang: 'nl', pack: PACK },
  { text: 'koningsdag', lang: 'nl', pack: PACK },
  { text: 'sinterklaas', lang: 'nl', pack: PACK },
  { text: 'kerstmarkt', lang: 'nl', pack: PACK },
  { text: 'oud en nieuw', lang: 'nl', pack: PACK },
  { text: 'vuurwerk', lang: 'nl', pack: PACK },
  { text: 'oliebollenkraam', lang: 'nl', pack: PACK },
  { text: 'terras', lang: 'nl', pack: PACK },
  { text: 'bruin café', lang: 'nl', pack: PACK },
  { text: 'coffeeshop', lang: 'nl', pack: PACK },
  { text: 'snackbar', lang: 'nl', pack: PACK },
  { text: 'patatzaak', lang: 'nl', pack: PACK },
  { text: 'visboer', lang: 'nl', pack: PACK },
  { text: 'bakker', lang: 'nl', pack: PACK },
  { text: 'slager', lang: 'nl', pack: PACK },
  { text: 'kapper', lang: 'nl', pack: PACK },
  { text: 'sauna', lang: 'nl', pack: PACK },
  { text: 'zwembad', lang: 'nl', pack: PACK },
  { text: 'sportschool', lang: 'nl', pack: PACK },
  { text: 'voetbalveld', lang: 'nl', pack: PACK },
  { text: 'ijsstadion', lang: 'nl', pack: PACK },
  { text: 'schaatsbaan', lang: 'nl', pack: PACK },
  { text: 'speeltuin', lang: 'nl', pack: PACK },
  { text: 'bos', lang: 'nl', pack: PACK },
  { text: 'duinen', lang: 'nl', pack: PACK },
  { text: 'polder', lang: 'nl', pack: PACK },
  { text: 'dijk', lang: 'nl', pack: PACK },
  { text: 'sloot', lang: 'nl', pack: PACK },
  { text: 'molenwiek', lang: 'nl', pack: PACK },
  { text: 'klokkentoren', lang: 'nl', pack: PACK },
  { text: 'stadhuis', lang: 'nl', pack: PACK },
  { text: 'bibliotheek', lang: 'nl', pack: PACK },
  { text: 'zwemband', lang: 'nl', pack: PACK },
  { text: 'regenjas', lang: 'nl', pack: PACK },
  { text: 'paraplu', lang: 'nl', pack: PACK },
  { text: 'fietstas', lang: 'nl', pack: PACK },
  { text: 'bagagedrager', lang: 'nl', pack: PACK },
  { text: 'trambaan', lang: 'nl', pack: PACK },
  { text: 'metro', lang: 'nl', pack: PACK },
  { text: 'veerboot', lang: 'nl', pack: PACK },
  { text: 'pont', lang: 'nl', pack: PACK },
  { text: 'waterfiets', lang: 'nl', pack: PACK },
  { text: 'kano', lang: 'nl', pack: PACK },
  { text: 'zeilboot', lang: 'nl', pack: PACK },
  { text: 'woonboot', lang: 'nl', pack: PACK },
  { text: 'huisje-boompje-beestje', lang: 'nl', pack: PACK },
  { text: 'buren', lang: 'nl', pack: PACK },
  { text: 'postcode', lang: 'nl', pack: PACK },
  { text: 'kenteken', lang: 'nl', pack: PACK },
  { text: 'rijbewijs', lang: 'nl', pack: PACK },
  { text: 'BSN', lang: 'nl', pack: PACK },
  { text: 'DigiD', lang: 'nl', pack: PACK },
  { text: 'iDEAL', lang: 'nl', pack: PACK },
  { text: 'pinpas', lang: 'nl', pack: PACK },
  { text: 'contant', lang: 'nl', pack: PACK },
  { text: 'fooienpot', lang: 'nl', pack: PACK },
  { text: 'borrel', lang: 'nl', pack: PACK },
  { text: 'borrelnootjes', lang: 'nl', pack: PACK },
  { text: 'kaasstengels', lang: 'nl', pack: PACK },
  { text: 'bittergarnituur', lang: 'nl', pack: PACK },
  { text: 'jenever', lang: 'nl', pack: PACK },
  { text: 'advocaat', lang: 'nl', pack: PACK },
  { text: 'likeuretje', lang: 'nl', pack: PACK },
  { text: 'witte wijn', lang: 'nl', pack: PACK },
  { text: 'rode wijn', lang: 'nl', pack: PACK },
  { text: 'Spa rood', lang: 'nl', pack: PACK },
  { text: 'Spa blauw', lang: 'nl', pack: PACK },
  { text: 'Chocomel', lang: 'nl', pack: PACK },
  { text: 'Fristi', lang: 'nl', pack: PACK },
  { text: 'Rivella', lang: 'nl', pack: PACK },
  { text: 'Grolsch', lang: 'nl', pack: PACK },
  { text: 'Heineken', lang: 'nl', pack: PACK },
  { text: 'Amstel', lang: 'nl', pack: PACK },
  { text: 'Bavaria', lang: 'nl', pack: PACK },
  { text: 'Jupiler', lang: 'nl', pack: PACK },
  { text: 'Big Brother', lang: 'nl', pack: PACK },
  { text: 'The Voice', lang: 'nl', pack: PACK },
  { text: 'Wie is de Mol', lang: 'nl', pack: PACK },
  { text: 'Boer zoekt Vrouw', lang: 'nl', pack: PACK },
  { text: 'Expeditie Robinson', lang: 'nl', pack: PACK },
  { text: 'Flikken Maastricht', lang: 'nl', pack: PACK },
  { text: 'Baantjer', lang: 'nl', pack: PACK },
  { text: 'Goede Tijden', lang: 'nl', pack: PACK },
  { text: 'Sesamstraat', lang: 'nl', pack: PACK },
  { text: 'Bassie en Adriaan', lang: 'nl', pack: PACK },
  { text: 'Kameleon', lang: 'nl', pack: PACK },
  { text: 'Piet Piraat', lang: 'nl', pack: PACK },
  { text: 'Samson en Gert', lang: 'nl', pack: PACK },
  { text: 'K3', lang: 'nl', pack: PACK },
  { text: 'Plop', lang: 'nl', pack: PACK },
  { text: 'Nijntje', lang: 'nl', pack: PACK },
  { text: 'Dikkie Dik', lang: 'nl', pack: PACK },
  { text: 'Jip en Janneke', lang: 'nl', pack: PACK },
  { text: 'Kikker', lang: 'nl', pack: PACK },
  { text: 'Dolfje Weerwolfje', lang: 'nl', pack: PACK },
  { text: 'Harry Potter', lang: 'nl', pack: PACK },
  { text: 'Koning van Katoren', lang: 'nl', pack: PACK },
  { text: 'Kruistocht in spijkerbroek', lang: 'nl', pack: PACK },
  { text: 'Oorlogswinter', lang: 'nl', pack: PACK },
  { text: 'Soldaat van Oranje', lang: 'nl', pack: PACK },
  { text: 'Zwarte Piet', lang: 'nl', pack: PACK },
  { text: 'Kerstman', lang: 'nl', pack: PACK },
  { text: 'Paashaas', lang: 'nl', pack: PACK },
  { text: 'tandenfee', lang: 'nl', pack: PACK },
  { text: 'Sinterklaasjournaal', lang: 'nl', pack: PACK },
  { text: 'NOS Journaal', lang: 'nl', pack: PACK },
  { text: 'Hart van Nederland', lang: 'nl', pack: PACK },
  { text: 'RTL Boulevard', lang: 'nl', pack: PACK },
  { text: 'Shownieuws', lang: 'nl', pack: PACK },
  { text: 'De Wereld Draait Door', lang: 'nl', pack: PACK },
  { text: 'College Tour', lang: 'nl', pack: PACK },
  { text: 'Pauw', lang: 'nl', pack: PACK },
  { text: 'Jinek', lang: 'nl', pack: PACK },
  { text: 'Op1', lang: 'nl', pack: PACK },
  { text: 'Khalid & Sophie', lang: 'nl', pack: PACK },
  { text: 'Voetbal International', lang: 'nl', pack: PACK },
  { text: 'Studio Sport', lang: 'nl', pack: PACK },
  { text: 'Formule 1', lang: 'nl', pack: PACK },
  { text: 'Tour de France', lang: 'nl', pack: PACK },
  { text: 'Elfstedentocht', lang: 'nl', pack: PACK },
  { text: 'Vierdaagse', lang: 'nl', pack: PACK },
  { text: 'Pinkpop', lang: 'nl', pack: PACK },
  { text: 'Lowlands', lang: 'nl', pack: PACK },
  { text: 'Mysteryland', lang: 'nl', pack: PACK },
  { text: 'Tomorrowland', lang: 'nl', pack: PACK },
  { text: 'Koninginnedag', lang: 'nl', pack: PACK },
  { text: 'Bevrijdingsdag', lang: 'nl', pack: PACK },
  { text: 'Dodenherdenking', lang: 'nl', pack: PACK },
  { text: 'Prinsjesdag', lang: 'nl', pack: PACK },
  { text: 'troonrede', lang: 'nl', pack: PACK },
  { text: 'Eerste Kamer', lang: 'nl', pack: PACK },
  { text: 'Tweede Kamer', lang: 'nl', pack: PACK },
  { text: 'gemeenteraad', lang: 'nl', pack: PACK },
  { text: 'burgemeester', lang: 'nl', pack: PACK },
  { text: 'wethouder', lang: 'nl', pack: PACK },
  { text: 'koningshuis', lang: 'nl', pack: PACK },
  { text: 'gouden koets', lang: 'nl', pack: PACK },
  { text: 'balkon', lang: 'nl', pack: PACK },
  { text: 'Paleis Noordeinde', lang: 'nl', pack: PACK },
  { text: 'Huis ten Bosch', lang: 'nl', pack: PACK },
  { text: 'Paleis Soestdijk', lang: 'nl', pack: PACK },
  { text: 'Dam', lang: 'nl', pack: PACK },
  { text: 'Museumplein', lang: 'nl', pack: PACK },
  { text: 'Vondelpark', lang: 'nl', pack: PACK },
  { text: 'Kralingse Bos', lang: 'nl', pack: PACK },
  { text: 'Hoge Veluwe', lang: 'nl', pack: PACK },
  { text: 'Biesbosch', lang: 'nl', pack: PACK },
  { text: 'Oosterschelde', lang: 'nl', pack: PACK },
  { text: 'IJsselmeer', lang: 'nl', pack: PACK },
  { text: 'Noordzee', lang: 'nl', pack: PACK },
  { text: 'Rijn', lang: 'nl', pack: PACK },
  { text: 'Maas', lang: 'nl', pack: PACK },
  { text: 'Waal', lang: 'nl', pack: PACK },
  { text: 'IJssel', lang: 'nl', pack: PACK },
  { text: 'goudse kaas', lang: 'nl', pack: PACK },
  { text: 'edammer', lang: 'nl', pack: PACK },
  { text: 'leidse kaas', lang: 'nl', pack: PACK },
  { text: 'boerenkaas', lang: 'nl', pack: PACK },
  { text: 'smeerkaas', lang: 'nl', pack: PACK },
  { text: 'ontbijt', lang: 'nl', pack: PACK },
  { text: 'lunch', lang: 'nl', pack: PACK },
  { text: 'avondeten', lang: 'nl', pack: PACK },
  { text: 'tussendoortje', lang: 'nl', pack: PACK },
  { text: 'koffietijd', lang: 'nl', pack: PACK },
  { text: 'beschuit met muisjes', lang: 'nl', pack: PACK },
  { text: 'zwanger', lang: 'nl', pack: PACK },
  { text: 'kraamvisite', lang: 'nl', pack: PACK },
  { text: 'huiswarming', lang: 'nl', pack: PACK },
  { text: 'vrijgezellenfeest', lang: 'nl', pack: PACK },
  { text: 'bruiloft', lang: 'nl', pack: PACK },
  { text: 'begrafenis', lang: 'nl', pack: PACK },
  { text: 'sjaal', lang: 'nl', pack: PACK },
  { text: 'muts', lang: 'nl', pack: PACK },
  { text: 'handschoenen', lang: 'nl', pack: PACK },
  { text: 'klompenpad', lang: 'nl', pack: PACK },
  { text: 'wandelbos', lang: 'nl', pack: PACK },
  { text: 'natuurspeeltuin', lang: 'nl', pack: PACK },
  { text: 'kinderboerderij', lang: 'nl', pack: PACK },
  { text: 'minicamping', lang: 'nl', pack: PACK },
];
