const PACK = 'sports';
export const WORDS = [
  { text: 'football', lang: 'mix', pack: PACK },
  { text: 'soccer', lang: 'mix', pack: PACK },
  { text: 'American football', lang: 'mix', pack: PACK },
  { text: 'rugby', lang: 'mix', pack: PACK },
  { text: 'cricket', lang: 'mix', pack: PACK },
  { text: 'baseball', lang: 'mix', pack: PACK },
  { text: 'basketball', lang: 'mix', pack: PACK },
  { text: 'volleyball', lang: 'mix', pack: PACK },
  { text: 'handball', lang: 'mix', pack: PACK },
  { text: 'hockey', lang: 'mix', pack: PACK },
  { text: 'ice hockey', lang: 'mix', pack: PACK },
  { text: 'field hockey', lang: 'mix', pack: PACK },
  { text: 'tennis', lang: 'mix', pack: PACK },
  { text: 'table tennis', lang: 'mix', pack: PACK },
  { text: 'badminton', lang: 'mix', pack: PACK },
  { text: 'squash', lang: 'mix', pack: PACK },
  { text: 'golf', lang: 'mix', pack: PACK },
  { text: 'bowling', lang: 'mix', pack: PACK },
  { text: 'billiards', lang: 'mix', pack: PACK },
  { text: 'snooker', lang: 'mix', pack: PACK },
  { text: 'darts', lang: 'mix', pack: PACK },
  { text: 'archery', lang: 'mix', pack: PACK },
  { text: 'fencing', lang: 'mix', pack: PACK },
  { text: 'boxing', lang: 'mix', pack: PACK },
  { text: 'MMA', lang: 'mix', pack: PACK },
  { text: 'wrestling', lang: 'mix', pack: PACK },
  { text: 'judo', lang: 'mix', pack: PACK },
  { text: 'karate', lang: 'mix', pack: PACK },
  { text: 'taekwondo', lang: 'mix', pack: PACK },
  { text: 'kung fu', lang: 'mix', pack: PACK },
  { text: 'swimming', lang: 'mix', pack: PACK },
  { text: 'diving', lang: 'mix', pack: PACK },
  { text: 'water polo', lang: 'mix', pack: PACK },
  { text: 'synchronized swimming', lang: 'mix', pack: PACK },
  { text: 'rowing', lang: 'mix', pack: PACK },
  { text: 'sailing', lang: 'mix', pack: PACK },
  { text: 'surfing', lang: 'mix', pack: PACK },
  { text: 'windsurfing', lang: 'mix', pack: PACK },
  { text: 'kitesurfing', lang: 'mix', pack: PACK },
  { text: 'canoeing', lang: 'mix', pack: PACK },
  { text: 'kayaking', lang: 'mix', pack: PACK },
  { text: 'cycling', lang: 'mix', pack: PACK },
  { text: 'mountain biking', lang: 'mix', pack: PACK },
  { text: 'BMX', lang: 'mix', pack: PACK },
  { text: 'speed skating', lang: 'mix', pack: PACK },
  { text: 'figure skating', lang: 'mix', pack: PACK },
  { text: 'ice dancing', lang: 'mix', pack: PACK },
  { text: 'ski jumping', lang: 'mix', pack: PACK },
  { text: 'alpine skiing', lang: 'mix', pack: PACK },
  { text: 'cross-country skiing', lang: 'mix', pack: PACK },
  { text: 'snowboarding', lang: 'mix', pack: PACK },
  { text: 'bobsleigh', lang: 'mix', pack: PACK },
  { text: 'luge', lang: 'mix', pack: PACK },
  { text: 'skeleton', lang: 'mix', pack: PACK },
  { text: 'biathlon', lang: 'mix', pack: PACK },
  { text: 'athletics', lang: 'mix', pack: PACK },
  { text: 'marathon', lang: 'mix', pack: PACK },
  { text: 'sprint', lang: 'mix', pack: PACK },
  { text: 'hurdles', lang: 'mix', pack: PACK },
  { text: 'relay', lang: 'mix', pack: PACK },
  { text: 'long jump', lang: 'mix', pack: PACK },
  { text: 'high jump', lang: 'mix', pack: PACK },
  { text: 'pole vault', lang: 'mix', pack: PACK },
  { text: 'shot put', lang: 'mix', pack: PACK },
  { text: 'javelin', lang: 'mix', pack: PACK },
  { text: 'discus', lang: 'mix', pack: PACK },
  { text: 'hammer throw', lang: 'mix', pack: PACK },
  { text: 'decathlon', lang: 'mix', pack: PACK },
  { text: 'triathlon', lang: 'mix', pack: PACK },
  { text: 'pentathlon', lang: 'mix', pack: PACK },
  { text: 'gymnastics', lang: 'mix', pack: PACK },
  { text: 'rhythmic gymnastics', lang: 'mix', pack: PACK },
  { text: 'trampolining', lang: 'mix', pack: PACK },
  { text: 'weightlifting', lang: 'mix', pack: PACK },
  { text: 'powerlifting', lang: 'mix', pack: PACK },
  { text: 'climbing', lang: 'mix', pack: PACK },
  { text: 'bouldering', lang: 'mix', pack: PACK },
  { text: 'orienteering', lang: 'mix', pack: PACK },
  { text: 'horse riding', lang: 'mix', pack: PACK },
  { text: 'dressage', lang: 'mix', pack: PACK },
  { text: 'show jumping', lang: 'mix', pack: PACK },
  { text: 'polo', lang: 'mix', pack: PACK },
  { text: 'formula 1', lang: 'mix', pack: PACK },
  { text: 'MotoGP', lang: 'mix', pack: PACK },
  { text: 'rally', lang: 'mix', pack: PACK },
  { text: 'NASCAR', lang: 'mix', pack: PACK },
  { text: 'IndyCar', lang: 'mix', pack: PACK },
  { text: 'karting', lang: 'mix', pack: PACK },
  { text: 'e-sports', lang: 'mix', pack: PACK },
  { text: 'chess', lang: 'mix', pack: PACK },
  { text: 'poker', lang: 'mix', pack: PACK },
  { text: 'bridge', lang: 'mix', pack: PACK },
  { text: 'curling', lang: 'mix', pack: PACK },
  { text: 'lacrosse', lang: 'mix', pack: PACK },
  { text: 'Gaelic football', lang: 'mix', pack: PACK },
  { text: 'Max Verstappen', lang: 'mix', pack: PACK },
  { text: 'Lewis Hamilton', lang: 'mix', pack: PACK },
  { text: 'Michael Schumacher', lang: 'mix', pack: PACK },
  { text: 'Ayrton Senna', lang: 'mix', pack: PACK },
  { text: 'Sebastian Vettel', lang: 'mix', pack: PACK },
  { text: 'Charles Leclerc', lang: 'mix', pack: PACK },
  { text: 'Lando Norris', lang: 'mix', pack: PACK },
  { text: 'Fernando Alonso', lang: 'mix', pack: PACK },
  { text: 'Kimi Räikkönen', lang: 'mix', pack: PACK },
  { text: 'Niki Lauda', lang: 'mix', pack: PACK },
  { text: 'Red Bull Racing', lang: 'mix', pack: PACK },
  { text: 'Ferrari', lang: 'mix', pack: PACK },
  { text: 'Mercedes', lang: 'mix', pack: PACK },
  { text: 'McLaren', lang: 'mix', pack: PACK },
  { text: 'Aston Martin', lang: 'mix', pack: PACK },
  { text: 'Lionel Messi', lang: 'mix', pack: PACK },
  { text: 'Cristiano Ronaldo', lang: 'mix', pack: PACK },
  { text: 'Pelé', lang: 'mix', pack: PACK },
  { text: 'Diego Maradona', lang: 'mix', pack: PACK },
  { text: 'Zinedine Zidane', lang: 'mix', pack: PACK },
  { text: 'Ronaldinho', lang: 'mix', pack: PACK },
  { text: 'Neymar', lang: 'mix', pack: PACK },
  { text: 'Kylian Mbappé', lang: 'mix', pack: PACK },
  { text: 'Erling Haaland', lang: 'mix', pack: PACK },
  { text: 'Kevin De Bruyne', lang: 'mix', pack: PACK },
  { text: 'Johan Cruijff', lang: 'mix', pack: PACK },
  { text: 'Marco van Basten', lang: 'mix', pack: PACK },
  { text: 'Ruud Gullit', lang: 'mix', pack: PACK },
  { text: 'Frank Rijkaard', lang: 'mix', pack: PACK },
  { text: 'Dennis Bergkamp', lang: 'mix', pack: PACK },
  { text: 'Patrick Kluivert', lang: 'mix', pack: PACK },
  { text: 'Edgar Davids', lang: 'mix', pack: PACK },
  { text: 'Clarence Seedorf', lang: 'mix', pack: PACK },
  { text: 'Wesley Sneijder', lang: 'mix', pack: PACK },
  { text: 'Arjen Robben', lang: 'mix', pack: PACK },
  { text: 'Robin van Persie', lang: 'mix', pack: PACK },
  { text: 'Dirk Kuyt', lang: 'mix', pack: PACK },
  { text: 'Rafael van der Vaart', lang: 'mix', pack: PACK },
  { text: 'Memphis Depay', lang: 'mix', pack: PACK },
  { text: 'Virgil van Dijk', lang: 'mix', pack: PACK },
  { text: 'Frenkie de Jong', lang: 'mix', pack: PACK },
  { text: 'Matthijs de Ligt', lang: 'mix', pack: PACK },
  { text: 'Cody Gakpo', lang: 'mix', pack: PACK },
  { text: 'Xavi Simons', lang: 'mix', pack: PACK },
  { text: 'Donyell Malen', lang: 'mix', pack: PACK },
  { text: 'Ajax', lang: 'mix', pack: PACK },
  { text: 'Feyenoord', lang: 'mix', pack: PACK },
  { text: 'PSV', lang: 'mix', pack: PACK },
  { text: 'AZ Alkmaar', lang: 'mix', pack: PACK },
  { text: 'FC Utrecht', lang: 'mix', pack: PACK },
  { text: 'FC Twente', lang: 'mix', pack: PACK },
  { text: 'Vitesse', lang: 'mix', pack: PACK },
  { text: 'Sparta Rotterdam', lang: 'mix', pack: PACK },
  { text: 'NEC Nijmegen', lang: 'mix', pack: PACK },
  { text: 'Go Ahead Eagles', lang: 'mix', pack: PACK },
  { text: 'Manchester United', lang: 'mix', pack: PACK },
  { text: 'Manchester City', lang: 'mix', pack: PACK },
  { text: 'Liverpool', lang: 'mix', pack: PACK },
  { text: 'Arsenal', lang: 'mix', pack: PACK },
  { text: 'Chelsea', lang: 'mix', pack: PACK },
  { text: 'Tottenham', lang: 'mix', pack: PACK },
  { text: 'Real Madrid', lang: 'mix', pack: PACK },
  { text: 'Barcelona', lang: 'mix', pack: PACK },
  { text: 'Atlético Madrid', lang: 'mix', pack: PACK },
  { text: 'Bayern Munich', lang: 'mix', pack: PACK },
  { text: 'Borussia Dortmund', lang: 'mix', pack: PACK },
  { text: 'Juventus', lang: 'mix', pack: PACK },
  { text: 'AC Milan', lang: 'mix', pack: PACK },
  { text: 'Inter Milan', lang: 'mix', pack: PACK },
  { text: 'Napoli', lang: 'mix', pack: PACK },
  { text: 'Paris Saint-Germain', lang: 'mix', pack: PACK },
  { text: 'Benfica', lang: 'mix', pack: PACK },
  { text: 'Porto', lang: 'mix', pack: PACK },
  { text: 'Sporting Lisbon', lang: 'mix', pack: PACK },
  { text: 'Celtic', lang: 'mix', pack: PACK },
  { text: 'World Cup', lang: 'mix', pack: PACK },
  { text: 'European Championship', lang: 'mix', pack: PACK },
  { text: 'Champions League', lang: 'mix', pack: PACK },
  { text: 'Europa League', lang: 'mix', pack: PACK },
  { text: 'Eredivisie', lang: 'mix', pack: PACK },
  { text: 'Premier League', lang: 'mix', pack: PACK },
  { text: 'La Liga', lang: 'mix', pack: PACK },
  { text: 'Bundesliga', lang: 'mix', pack: PACK },
  { text: 'Serie A', lang: 'mix', pack: PACK },
  { text: 'Ligue 1', lang: 'mix', pack: PACK },
  { text: 'Super Bowl', lang: 'mix', pack: PACK },
  { text: 'NBA Finals', lang: 'mix', pack: PACK },
  { text: 'World Series', lang: 'mix', pack: PACK },
  { text: 'Stanley Cup', lang: 'mix', pack: PACK },
  { text: 'Wimbledon', lang: 'mix', pack: PACK },
  { text: 'Roland Garros', lang: 'mix', pack: PACK },
  { text: 'US Open', lang: 'mix', pack: PACK },
  { text: 'Australian Open', lang: 'mix', pack: PACK },
  { text: 'The Masters', lang: 'mix', pack: PACK },
  { text: 'Tour de France', lang: 'mix', pack: PACK },
  { text: "Giro d'Italia", lang: 'mix', pack: PACK },
  { text: 'Vuelta', lang: 'mix', pack: PACK },
  { text: 'Olympics', lang: 'mix', pack: PACK },
  { text: 'Paralympics', lang: 'mix', pack: PACK },
  { text: 'Commonwealth Games', lang: 'mix', pack: PACK },
  { text: 'Roger Federer', lang: 'mix', pack: PACK },
  { text: 'Rafael Nadal', lang: 'mix', pack: PACK },
  { text: 'Novak Djokovic', lang: 'mix', pack: PACK },
  { text: 'Serena Williams', lang: 'mix', pack: PACK },
  { text: 'Venus Williams', lang: 'mix', pack: PACK },
  { text: 'Steffi Graf', lang: 'mix', pack: PACK },
  { text: 'Andre Agassi', lang: 'mix', pack: PACK },
  { text: 'Pete Sampras', lang: 'mix', pack: PACK },
  { text: 'Maria Sharapova', lang: 'mix', pack: PACK },
  { text: 'Naomi Osaka', lang: 'mix', pack: PACK },
  { text: 'Iga Świątek', lang: 'mix', pack: PACK },
  { text: 'Carlos Alcaraz', lang: 'mix', pack: PACK },
  { text: 'Jannik Sinner', lang: 'mix', pack: PACK },
  { text: 'Andy Murray', lang: 'mix', pack: PACK },
  { text: 'Richard Krajicek', lang: 'mix', pack: PACK },
  { text: 'Michael Jordan', lang: 'mix', pack: PACK },
  { text: 'LeBron James', lang: 'mix', pack: PACK },
  { text: 'Kobe Bryant', lang: 'mix', pack: PACK },
  { text: 'Magic Johnson', lang: 'mix', pack: PACK },
  { text: 'Larry Bird', lang: 'mix', pack: PACK },
  { text: "Shaquille O'Neal", lang: 'mix', pack: PACK },
  { text: 'Stephen Curry', lang: 'mix', pack: PACK },
  { text: 'Kevin Durant', lang: 'mix', pack: PACK },
  { text: 'Giannis Antetokounmpo', lang: 'mix', pack: PACK },
  { text: 'Dirk Nowitzki', lang: 'mix', pack: PACK },
  { text: 'Tiger Woods', lang: 'mix', pack: PACK },
  { text: 'Jack Nicklaus', lang: 'mix', pack: PACK },
  { text: 'Rory McIlroy', lang: 'mix', pack: PACK },
  { text: 'Annika Sörenstam', lang: 'mix', pack: PACK },
  { text: 'Joost Luiten', lang: 'mix', pack: PACK },
  { text: 'Usain Bolt', lang: 'mix', pack: PACK },
  { text: 'Carl Lewis', lang: 'mix', pack: PACK },
  { text: 'Mo Farah', lang: 'mix', pack: PACK },
  { text: 'Eliud Kipchoge', lang: 'mix', pack: PACK },
  { text: 'Fanny Blankers-Koen', lang: 'mix', pack: PACK },
  { text: 'Dafne Schippers', lang: 'mix', pack: PACK },
  { text: 'Sifan Hassan', lang: 'mix', pack: PACK },
  { text: 'Femke Bol', lang: 'mix', pack: PACK },
  { text: 'Nelli Cooman', lang: 'mix', pack: PACK },
  { text: 'Ria Stalman', lang: 'mix', pack: PACK },
  { text: 'Pieter van den Hoogenband', lang: 'mix', pack: PACK },
  { text: 'Inge de Bruijn', lang: 'mix', pack: PACK },
  { text: 'Ranomi Kromowidjojo', lang: 'mix', pack: PACK },
  { text: 'Marleen Veldhuis', lang: 'mix', pack: PACK },
  { text: 'Ireen Wüst', lang: 'mix', pack: PACK },
  { text: 'Sven Kramer', lang: 'mix', pack: PACK },
  { text: 'Jorrit Bergsma', lang: 'mix', pack: PACK },
  { text: 'Kjeld Nuis', lang: 'mix', pack: PACK },
  { text: 'Jutta Leerdam', lang: 'mix', pack: PACK },
  { text: 'Irene Schouten', lang: 'mix', pack: PACK },
  { text: 'Ard Schenk', lang: 'mix', pack: PACK },
  { text: 'Kees Verkerk', lang: 'mix', pack: PACK },
  { text: 'Yvonne van Gennip', lang: 'mix', pack: PACK },
  { text: 'Marianne Timmer', lang: 'mix', pack: PACK },
  { text: 'Anni Friesinger', lang: 'mix', pack: PACK },
  { text: 'Epke Zonderland', lang: 'mix', pack: PACK },
  { text: 'Sanne Wevers', lang: 'mix', pack: PACK },
  { text: 'Max Whitlock', lang: 'mix', pack: PACK },
  { text: 'Esther Vergeer', lang: 'mix', pack: PACK },
  { text: 'Diede de Groot', lang: 'mix', pack: PACK },
  { text: 'Tom Dumoulin', lang: 'mix', pack: PACK },
  { text: 'Mathieu van der Poel', lang: 'mix', pack: PACK },
  { text: 'Wout van Aert', lang: 'mix', pack: PACK },
  { text: 'Marianne Vos', lang: 'mix', pack: PACK },
  { text: 'Anna van der Breggen', lang: 'mix', pack: PACK },
  { text: 'Leontien van Moorsel', lang: 'mix', pack: PACK },
  { text: 'Erik Dekker', lang: 'mix', pack: PACK },
  { text: 'Joop Zoetemelk', lang: 'mix', pack: PACK },
  { text: 'Jan Janssen', lang: 'mix', pack: PACK },
  { text: 'Peter Post', lang: 'mix', pack: PACK },
  { text: 'AFC Ajax', lang: 'mix', pack: PACK },
  { text: 'De Kuip', lang: 'mix', pack: PACK },
  { text: 'Johan Cruijff ArenA', lang: 'mix', pack: PACK },
  { text: 'Philips Stadion', lang: 'mix', pack: PACK },
  { text: 'Cars Jeans Stadion', lang: 'mix', pack: PACK },
  { text: 'offside', lang: 'mix', pack: PACK },
  { text: 'penalty', lang: 'mix', pack: PACK },
  { text: 'corner kick', lang: 'mix', pack: PACK },
  { text: 'free kick', lang: 'mix', pack: PACK },
  { text: 'own goal', lang: 'mix', pack: PACK },
  { text: 'hat-trick', lang: 'mix', pack: PACK },
  { text: 'red card', lang: 'mix', pack: PACK },
  { text: 'yellow card', lang: 'mix', pack: PACK },
  { text: 'VAR', lang: 'mix', pack: PACK },
  { text: 'goalkeeper', lang: 'mix', pack: PACK },
  { text: 'striker', lang: 'mix', pack: PACK },
  { text: 'midfielder', lang: 'mix', pack: PACK },
  { text: 'defender', lang: 'mix', pack: PACK },
  { text: 'captain', lang: 'mix', pack: PACK },
  { text: 'manager', lang: 'mix', pack: PACK },
  { text: 'knockout', lang: 'mix', pack: PACK },
  { text: 'uppercut', lang: 'mix', pack: PACK },
  { text: 'jab', lang: 'mix', pack: PACK },
  { text: 'slam dunk', lang: 'mix', pack: PACK },
  { text: 'three-pointer', lang: 'mix', pack: PACK },
  { text: 'home run', lang: 'mix', pack: PACK },
  { text: 'touchdown', lang: 'mix', pack: PACK },
  { text: 'ace', lang: 'mix', pack: PACK },
  { text: 'deuce', lang: 'mix', pack: PACK },
  { text: 'break point', lang: 'mix', pack: PACK },
  { text: 'birdie', lang: 'mix', pack: PACK },
  { text: 'eagle', lang: 'mix', pack: PACK },
  { text: 'hole in one', lang: 'mix', pack: PACK },
  { text: 'albatross', lang: 'mix', pack: PACK },
  { text: 'par', lang: 'mix', pack: PACK },
  { text: 'photo finish', lang: 'mix', pack: PACK },
  { text: 'world record', lang: 'mix', pack: PACK },
  { text: 'personal best', lang: 'mix', pack: PACK },
  { text: 'gold medal', lang: 'mix', pack: PACK },
  { text: 'silver medal', lang: 'mix', pack: PACK },
  { text: 'bronze medal', lang: 'mix', pack: PACK },
  { text: 'podium', lang: 'mix', pack: PACK },
  { text: 'lap of honour', lang: 'mix', pack: PACK },
  { text: 'mascot', lang: 'mix', pack: PACK },
  { text: 'opening ceremony', lang: 'mix', pack: PACK },
  { text: 'torch', lang: 'mix', pack: PACK },
  { text: 'stadium', lang: 'mix', pack: PACK },
  { text: 'arena', lang: 'mix', pack: PACK },
  { text: 'pitch', lang: 'mix', pack: PACK },
  { text: 'court', lang: 'mix', pack: PACK },
  { text: 'rink', lang: 'mix', pack: PACK },
  { text: 'pool', lang: 'mix', pack: PACK },
  { text: 'track', lang: 'mix', pack: PACK },
  { text: 'velodrome', lang: 'mix', pack: PACK },
  { text: 'piste', lang: 'mix', pack: PACK },
  { text: 'coach', lang: 'mix', pack: PACK },
  { text: 'referee', lang: 'mix', pack: PACK },
  { text: 'umpire', lang: 'mix', pack: PACK },
  { text: 'linesman', lang: 'mix', pack: PACK },
  { text: 'steward', lang: 'mix', pack: PACK },
  { text: 'fan', lang: 'mix', pack: PACK },
  { text: 'ultras', lang: 'mix', pack: PACK },
  { text: 'derby', lang: 'mix', pack: PACK },
  { text: 'clásico', lang: 'mix', pack: PACK },
  { text: 'play-off', lang: 'mix', pack: PACK },
  { text: 'relegation', lang: 'mix', pack: PACK },
  { text: 'promotion', lang: 'mix', pack: PACK },
  { text: 'transfer', lang: 'mix', pack: PACK },
  { text: 'loan', lang: 'mix', pack: PACK },
  { text: 'free agent', lang: 'mix', pack: PACK },
  { text: 'KNVB', lang: 'mix', pack: PACK },
  { text: 'FIFA', lang: 'mix', pack: PACK },
  { text: 'UEFA', lang: 'mix', pack: PACK },
  { text: 'IOC', lang: 'mix', pack: PACK },
  { text: 'FIFA World Cup', lang: 'mix', pack: PACK },
  { text: 'Davis Cup', lang: 'mix', pack: PACK },
  { text: 'Ryder Cup', lang: 'mix', pack: PACK },
  { text: "America's Cup", lang: 'mix', pack: PACK },
  { text: 'Rugby World Cup', lang: 'mix', pack: PACK },
  { text: 'Cricket World Cup', lang: 'mix', pack: PACK },
  { text: 'NBA', lang: 'mix', pack: PACK },
  { text: 'NFL', lang: 'mix', pack: PACK },
  { text: 'MLB', lang: 'mix', pack: PACK },
  { text: 'NHL', lang: 'mix', pack: PACK },
  { text: 'PGA Tour', lang: 'mix', pack: PACK },
  { text: 'Formule 1', lang: 'mix', pack: PACK },
  { text: 'Dakar Rally', lang: 'mix', pack: PACK },
  { text: 'Le Mans', lang: 'mix', pack: PACK },
  { text: 'Indy 500', lang: 'mix', pack: PACK },
  { text: 'Elfstedentocht', lang: 'mix', pack: PACK },
  { text: 'Vierdaagse', lang: 'mix', pack: PACK },
  { text: 'Amsterdam Marathon', lang: 'mix', pack: PACK },
  { text: 'Rotterdam Marathon', lang: 'mix', pack: PACK },
  { text: "Alpe d'HuZes", lang: 'mix', pack: PACK },
  { text: 'Hockey World Cup', lang: 'mix', pack: PACK },
  { text: 'FIH Pro League', lang: 'mix', pack: PACK },
  { text: 'Orange Lions', lang: 'mix', pack: PACK },
  { text: 'Orange Women', lang: 'mix', pack: PACK },
  { text: 'Oranje', lang: 'mix', pack: PACK },
  { text: 'keirin', lang: 'mix', pack: PACK },
  { text: 'madison', lang: 'mix', pack: PACK },
  { text: 'omnium', lang: 'mix', pack: PACK },
  { text: 'pursuit', lang: 'mix', pack: PACK },
  { text: 'time trial', lang: 'mix', pack: PACK },
  { text: 'butterfly', lang: 'mix', pack: PACK },
  { text: 'backstroke', lang: 'mix', pack: PACK },
  { text: 'breaststroke', lang: 'mix', pack: PACK },
  { text: 'freestyle', lang: 'mix', pack: PACK },
  { text: 'medley', lang: 'mix', pack: PACK },
  { text: 'halfpipe', lang: 'mix', pack: PACK },
  { text: 'slalom', lang: 'mix', pack: PACK },
  { text: 'downhill', lang: 'mix', pack: PACK },
  { text: 'super-G', lang: 'mix', pack: PACK },
  { text: 'moguls', lang: 'mix', pack: PACK },
  { text: 'sumo', lang: 'mix', pack: PACK },
  { text: 'kabaddi', lang: 'mix', pack: PACK },
  { text: 'sepak takraw', lang: 'mix', pack: PACK },
  { text: 'petanque', lang: 'mix', pack: PACK },
  { text: 'korfbal', lang: 'mix', pack: PACK },
  { text: 'Honkbal', lang: 'mix', pack: PACK },
  { text: 'softbal', lang: 'mix', pack: PACK },
  { text: 'beachvolleybal', lang: 'mix', pack: PACK },
  { text: 'zaalvoetbal', lang: 'mix', pack: PACK },
  { text: 'waterpolo', lang: 'mix', pack: PACK },
];
